//! Secret redaction: masks API keys, tokens, passwords, and similar secrets in hook payloads before anything
//! is written to disk.
//!
//! The rules are gitleaks' (v8.30.1, MIT, see `third_party/gitleaks/`), turned into a static table by
//! `build.rs`. A hook runs in a new process every time, so compiling all 221 regexes up front (about 50 ms)
//! is not an option. Instead, one case-insensitive pass over the text finds which rule keywords occur, and
//! only the rules with a keyword hit are compiled (once per process) and run. Text with no keyword costs a
//! single substring scan.
//!
//! Each match's secret (the rule's secret group, else the first non-empty group, else the whole match) is
//! kept when its Shannon entropy is at or above the rule's threshold, and replaced with
//! `[REDACTED:<rule-id>]`. gitleaks' allowlists and stopwords are not applied: masking a harmless value is
//! better than writing a real secret to disk.

use std::cmp::Reverse;
use std::fmt::Write as _;
use std::sync::OnceLock;

use aho_corasick::AhoCorasick;
use regex_automata::meta::{self, Regex};
use regex_automata::util::syntax;
use serde_json::Value;

/// Longer strings are cut to this many bytes and end with `[TRUNCATED: <original length> bytes in total]`.
pub const MAX_STRING_BYTES: usize = 256 * 1024;

/// The most text one [`redact_json`] call scans. Running every rule costs about 200 ns per byte, and
/// hostile text (a file the agent reads, a command's output) can contain every keyword, so without this
/// bound a 64 MiB payload could hold up the agent for many seconds; with it, the worst case measured on a
/// Windows laptop is about 0.4 s. Once it is used up, every further string is replaced by its truncation
/// marker. Real payloads stay far below it.
pub const MAX_JSON_TEXT_BYTES: usize = 1024 * 1024;

/// What each string costs from [`MAX_JSON_TEXT_BYTES`] on top of its length: the fixed work of scanning
/// one string, so that a payload of millions of tiny strings is bounded too.
const STRING_COST_BYTES: usize = 64;

/// How far past the cut a long string is still scanned, so a secret that straddles the cut is masked
/// instead of leaving its first bytes behind. Larger than any realistic secret, including a PEM private
/// key block.
const CUT_OVERLAP_BYTES: usize = 16 * 1024;

/// One gitleaks rule, as generated by `build.rs`.
struct Rule {
    id: &'static str,
    regex: &'static str,
    /// The capture group holding the secret, or 0 to use the first non-empty group (or the whole match).
    secret_group: usize,
    /// Minimum Shannon entropy of the secret, in bits per byte; 0 means no check.
    entropy: f64,
}

// Defines `RULE_COUNT`, `RULES`, `KEYWORDS` (lowercase, sorted) and `KEYWORD_RULES` (for each keyword,
// the indexes of the rules that list it).
include!(concat!(env!("OUT_DIR"), "/gitleaks_rules.rs"));

/// Redacts every string in `value`, object keys included, in place, in document order. Each string is cut to
/// [`MAX_STRING_BYTES`] and the whole value to [`MAX_JSON_TEXT_BYTES`] first.
pub fn redact_json(value: &mut Value) {
    let mut budget = MAX_JSON_TEXT_BYTES;
    redact_value(value, &mut budget);
}

/// `text` with its secrets masked and cut to [`MAX_STRING_BYTES`], or `None` when it is unchanged.
pub fn redact_str(text: &str) -> Option<String> {
    redact_cut(text, MAX_STRING_BYTES)
}

/// Appended to a string that was cut, with the original length so the record shows how much was dropped.
fn truncation_marker(original_bytes: usize) -> String {
    format!("[TRUNCATED: {original_bytes} bytes in total]")
}

fn redact_value(value: &mut Value, budget: &mut usize) {
    match value {
        Value::String(text) => {
            if let Some(redacted) = redact_charged(text, budget) {
                *text = redacted;
            }
        }
        Value::Array(items) => items.iter_mut().for_each(|item| redact_value(item, budget)),
        Value::Object(map) => {
            // Keys are rebuilt in their original order. If two keys become equal after redaction (or after
            // the budget ran out), the later entry replaces the earlier one.
            for (key, mut item) in std::mem::take(map) {
                let key = redact_charged(&key, budget).unwrap_or(key);
                redact_value(&mut item, budget);
                map.insert(key, item);
            }
        }
        Value::Null | Value::Bool(_) | Value::Number(_) => {}
    }
}

/// Redacts one string of a JSON value, cut to what is left of `budget`, and charges the budget.
fn redact_charged(text: &str, budget: &mut usize) -> Option<String> {
    let limit = (*budget).min(MAX_STRING_BYTES);
    *budget = budget.saturating_sub(text.len().min(limit) + STRING_COST_BYTES);
    redact_cut(text, limit)
}

/// `text` cut to at most `limit` bytes, with its secrets masked, or `None` when it is unchanged.
fn redact_cut(text: &str, limit: usize) -> Option<String> {
    let keep_end = floor_char_boundary(text, limit);
    let scan_end = if keep_end == 0 {
        0
    } else {
        floor_char_boundary(text, limit + CUT_OVERLAP_BYTES)
    };
    let secrets = find_secrets(&text[..scan_end]);
    if secrets.is_empty() && keep_end == text.len() {
        return None;
    }

    let mut redacted = String::with_capacity(keep_end + 64);
    let mut position = 0;
    for secret in secrets.iter().take_while(|secret| secret.start < keep_end) {
        redacted.push_str(&text[position..secret.start]);
        write!(redacted, "[REDACTED:{}]", RULES[secret.rule].id).unwrap();
        position = secret.end;
    }
    if position < keep_end {
        redacted.push_str(&text[position..keep_end]);
    }
    if keep_end < text.len() {
        redacted.push_str(&truncation_marker(text.len()));
    }
    Some(redacted)
}

/// A byte range of the text to mask, and the rule that found it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Secret {
    start: usize,
    end: usize,
    rule: usize,
}

/// The secrets in `text`, sorted and merged so that no two ranges overlap, on character boundaries.
fn find_secrets(text: &str) -> Vec<Secret> {
    let mut candidates = [false; RULE_COUNT];
    let mut any = false;
    for hit in keyword_finder().find_overlapping_iter(text) {
        for &rule in KEYWORD_RULES[hit.pattern().as_usize()] {
            candidates[usize::from(rule)] = true;
            any = true;
        }
    }
    if !any {
        return Vec::new();
    }

    let bytes = text.as_bytes();
    let mut secrets = Vec::new();
    for (index, rule) in RULES.iter().enumerate() {
        if !candidates[index] {
            continue;
        }
        let Some(regex) = compiled(index) else {
            continue;
        };
        for captures in regex.captures_iter(bytes) {
            let secret = if rule.secret_group > 0 {
                captures.get_group(rule.secret_group)
            } else {
                (1..captures.group_len())
                    .filter_map(|group| captures.get_group(group))
                    .find(|group| !group.is_empty())
                    .or_else(|| captures.get_group(0))
            };
            let Some(secret) = secret.filter(|secret| !secret.is_empty()) else {
                continue;
            };
            // gitleaks drops a match at or below the threshold; keeping the equal case masks slightly more.
            if rule.entropy > 0.0 && shannon_entropy(&bytes[secret.range()]) < rule.entropy {
                continue;
            }
            secrets.push(Secret {
                start: floor_char_boundary(text, secret.start),
                end: ceil_char_boundary(text, secret.end),
                rule: index,
            });
        }
    }

    secrets.sort_unstable_by_key(|secret| (secret.start, Reverse(secret.end), secret.rule));
    let mut merged: Vec<Secret> = Vec::with_capacity(secrets.len());
    for secret in secrets {
        match merged.last_mut() {
            Some(last) if secret.start < last.end => last.end = last.end.max(secret.end),
            _ => merged.push(secret),
        }
    }
    merged
}

/// The automaton over all rule keywords, built on first use.
fn keyword_finder() -> &'static AhoCorasick {
    static FINDER: OnceLock<AhoCorasick> = OnceLock::new();
    FINDER.get_or_init(|| {
        AhoCorasick::builder()
            .ascii_case_insensitive(true)
            .build(KEYWORDS)
            .expect("the rule keywords form a valid automaton")
    })
}

/// Rule `index`'s regex, compiled on first use. `None` if it does not compile (a test checks they all do).
fn compiled(index: usize) -> Option<&'static Regex> {
    static COMPILED: [OnceLock<Option<Regex>>; RULE_COUNT] =
        [const { OnceLock::new() }; RULE_COUNT];
    COMPILED[index]
        .get_or_init(|| build_regex(RULES[index].regex).ok())
        .as_ref()
}

/// Compiles a gitleaks regex with the engine behind the `regex` crate, configured like `regex::bytes`.
///
/// Go's RE2, which gitleaks uses, treats `\w`, `\s`, `\b` and `(?i)` as ASCII, so Unicode mode is off:
/// that is both the faithful port and about 90 times faster to compile. The one-pass DFA is off, since
/// captures only run on the span of a match. The literal prefilter is off for the 101 rules built from
/// gitleaks' semi-generic template (`[\w.-]{0,50}?` before a keyword, as in `generic-api-key`, which
/// nearly every payload triggers): it more than doubles their compile time and does not speed up their
/// search (measured). For the other rules it is cheap and makes the search much faster.
fn build_regex(pattern: &str) -> Result<Regex, Box<meta::BuildError>> {
    let semi_generic = pattern.contains(r"[\w.-]{0,50}?");
    meta::Builder::new()
        .configure(
            meta::Config::new()
                .utf8_empty(false)
                .onepass(false)
                .auto_prefilter(!semi_generic),
        )
        .syntax(syntax::Config::new().unicode(false).utf8(false))
        .build(pattern)
        .map_err(Box::new)
}

/// Shannon entropy in bits per byte. gitleaks counts characters instead; secrets are ASCII, where both agree.
fn shannon_entropy(bytes: &[u8]) -> f64 {
    let mut counts = [0u32; 256];
    for &byte in bytes {
        counts[usize::from(byte)] += 1;
    }
    let length = bytes.len() as f64;
    counts
        .iter()
        .filter(|&&count| count > 0)
        .map(|&count| {
            let frequency = f64::from(count) / length;
            -frequency * frequency.log2()
        })
        .sum()
}

fn floor_char_boundary(text: &str, mut index: usize) -> usize {
    if index >= text.len() {
        return text.len();
    }
    while !text.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn ceil_char_boundary(text: &str, mut index: usize) -> usize {
    while !text.is_char_boundary(index) {
        index += 1;
    }
    index
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    const ALNUM: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    const UPPER_BASE32: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
    const DIGITS: &[u8] = b"0123456789";

    /// A deterministic random-looking string. Fake secrets are built at run time from a prefix and this, so
    /// no complete token appears in the source.
    fn fake(alphabet: &[u8], length: usize, seed: u64) -> String {
        let mut state = seed;
        (0..length)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                char::from(alphabet[(state >> 33) as usize % alphabet.len()])
            })
            .collect()
    }

    fn redacted(text: &str) -> String {
        redact_str(text).unwrap_or_else(|| text.to_owned())
    }

    /// Asserts that `secret` is gone from the redacted `text`, replaced by `rule`'s marker, and returns the
    /// redacted text.
    #[track_caller]
    fn assert_masked(text: &str, secret: &str, rule: &str) -> String {
        let result = redacted(text);
        assert!(!result.contains(secret), "secret left in {result:?}");
        assert!(
            result.contains(&format!("[REDACTED:{rule}]")),
            "no {rule} marker in {result:?}"
        );
        result
    }

    #[test]
    fn every_rule_compiles_without_unicode() {
        assert_eq!(RULE_COUNT, 221, "gitleaks v8.30.1 has 221 regex rules");
        for rule in &RULES {
            if let Err(error) = build_regex(rule.regex) {
                panic!("rule {} does not compile: {error}", rule.id);
            }
        }
    }

    #[test]
    fn every_rule_is_reachable_through_a_lowercase_keyword() {
        let mut reachable = [false; RULE_COUNT];
        for (keyword, rules) in KEYWORDS.iter().zip(KEYWORD_RULES) {
            assert_eq!(*keyword, keyword.to_ascii_lowercase());
            for &rule in rules {
                reachable[usize::from(rule)] = true;
            }
        }
        assert!(reachable.iter().all(|&reachable| reachable));
    }

    #[test]
    fn cloud_provider_access_keys() {
        let aws = format!("AKIA{}", fake(UPPER_BASE32, 16, 1));
        let text = format!("[default]\naws_access_key_id={aws}\nregion=eu-west-3\n");
        let result = redacted(&text);
        assert!(!result.contains(&aws), "{result:?}");
        assert!(result.ends_with("]\nregion=eu-west-3\n"), "{result:?}");
        assert_masked(&format!("id {aws} in use"), &aws, "aws-access-token");

        let gcp = format!("AIza{}", fake(ALNUM, 35, 2));
        assert_masked(&format!("maps.load('{gcp}')"), &gcp, "gcp-api-key");
    }

    #[test]
    fn github_tokens() {
        let classic = format!("ghp_{}", fake(ALNUM, 36, 3));
        let result = assert_masked(
            &format!("git clone https://{classic}@github.com/o/r"),
            &classic,
            "github-pat",
        );
        assert_eq!(
            result,
            "git clone https://[REDACTED:github-pat]@github.com/o/r"
        );

        let fine_grained = format!("github_pat_{}", fake(ALNUM, 82, 4));
        assert_masked(
            &format!("use {fine_grained} here"),
            &fine_grained,
            "github-fine-grained-pat",
        );
    }

    #[test]
    fn llm_provider_api_keys() {
        let anthropic = format!("sk-ant-api03-{}AA", fake(ALNUM, 93, 5));
        assert_masked(
            &format!("client = Client('{anthropic}')"),
            &anthropic,
            "anthropic-api-key",
        );

        let openai = format!(
            "sk-proj-{}T3BlbkFJ{}",
            fake(ALNUM, 74, 6),
            fake(ALNUM, 74, 7)
        );
        assert_masked(
            &format!("OPENAI_API_KEY={openai}\n"),
            &openai,
            "openai-api-key",
        );

        let huggingface = format!(
            "hf_{}",
            fake(b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJ", 34, 8)
        );
        assert_masked(
            &format!("login {huggingface}\n"),
            &huggingface,
            "huggingface-access-token",
        );
    }

    #[test]
    fn slack_tokens() {
        let bot = format!(
            "xoxb-{}-{}-{}",
            fake(DIGITS, 12, 9),
            fake(DIGITS, 13, 10),
            fake(ALNUM, 24, 11)
        );
        assert_masked(&format!("SLACK={bot} ./post.sh"), &bot, "slack-bot-token");

        let webhook = format!("https://hooks.slack.com/services/{}", fake(ALNUM, 44, 12));
        assert_masked(
            &format!("curl -X POST {webhook}"),
            &webhook,
            "slack-webhook-url",
        );
    }

    #[test]
    fn private_key_block() {
        let body: Vec<String> = (0..12).map(|line| fake(ALNUM, 64, 100 + line)).collect();
        let block = format!(
            "-----BEGIN {kind} KEY-----\n{body}\n-----END {kind} KEY-----",
            kind = "RSA PRIVATE",
            body = body.join("\n")
        );
        let result = assert_masked(
            &format!("cat id_rsa\n{block}\ndone"),
            &body[5],
            "private-key",
        );
        assert_eq!(result, "cat id_rsa\n[REDACTED:private-key]\ndone");
    }

    #[test]
    fn json_web_token() {
        let jwt = format!(
            "eyJ{}.eyJ{}.{}",
            fake(ALNUM, 33, 13),
            fake(ALNUM, 60, 14),
            fake(ALNUM, 43, 15)
        );
        assert_masked(&format!("Cookie: session={jwt}; Path=/"), &jwt, "jwt");
    }

    #[test]
    fn generic_assignments() {
        let password = fake(ALNUM, 20, 16);
        let result = assert_masked(
            &format!("password={password}"),
            &password,
            "generic-api-key",
        );
        assert_eq!(result, "password=[REDACTED:generic-api-key]");

        let api_key = fake(ALNUM, 32, 17);
        let result = assert_masked(
            &format!("export API_KEY=\"{api_key}\"\n"),
            &api_key,
            "generic-api-key",
        );
        assert_eq!(result, "export API_KEY=\"[REDACTED:generic-api-key]\"\n");

        let secret = fake(ALNUM, 40, 18);
        assert_masked(
            &format!("{{\"client_secret\": \"{secret}\"}}"),
            &secret,
            "generic-api-key",
        );
    }

    #[test]
    fn low_entropy_values_are_kept() {
        // Below the generic rule's 3.5 bits per byte, as in gitleaks.
        for text in ["password=aaaaaaaaaaaaaaaa", "api_key = 1111111111222222"] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn secrets_inside_tool_input_and_tool_response() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 19));
        let password = fake(ALNUM, 24, 20);
        let mut payload = json!({
            "session_id": "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71",
            "hook_event_name": "PostToolUse",
            "tool_name": "Bash",
            "tool_input": {
                "command": format!("GH_TOKEN={github} gh pr list"),
                "env": { "nested": [1, true, null, { "deeper": format!("using {github}") }] },
            },
            "tool_response": {
                "stdout": format!("connecting with db_password: {password}\nok\n"),
                "stderr": "",
                "interrupted": false,
            },
        });
        redact_json(&mut payload);
        let text = payload.to_string();
        assert!(
            !text.contains(&github) && !text.contains(&password),
            "{text}"
        );
        assert_eq!(
            payload["tool_input"]["env"]["nested"][3]["deeper"],
            "using [REDACTED:github-pat]"
        );
        assert_eq!(
            payload["tool_response"]["stdout"],
            "connecting with db_password: [REDACTED:generic-api-key]\nok\n"
        );
        assert_eq!(
            payload["session_id"],
            "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71"
        );
        assert_eq!(payload["tool_input"]["env"]["nested"][0], 1);
        assert_eq!(payload["tool_response"]["interrupted"], false);
    }

    #[test]
    fn object_keys_are_redacted_in_place() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 21));
        let mut value = json!({ "a": 1, format!("token {github}"): 2, "z": 3 });
        redact_json(&mut value);
        let keys: Vec<&String> = value.as_object().unwrap().keys().collect();
        assert_eq!(keys.len(), 3);
        assert!(keys.iter().all(|key| !key.contains(&github)), "{keys:?}");
        assert_eq!(value["token [REDACTED:github-pat]"], 2);
    }

    #[test]
    fn git_shas_uuids_code_and_prose_are_unchanged() {
        let samples = [
            "commit 9fceb02d0ae598e95dc970b74767f19372d61af8\nAuthor: Dev <dev@example.com>\n\n    Fix parser\n",
            "3f786850e387550fdab836ed7e6dc881de23001b a1b2c3d HEAD@{0}: checkout: moving from main to fix",
            "session 4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71 resumed (request 0d9e3c3a-12f4-4bb1-9d0e-8f6f2a0c5b7e)",
            "fn verify(password: &str, hash: &PasswordHash) -> Result<(), Error> {\n    \
             let token = tokens.next().ok_or(Error::MissingToken)?;\n    \
             let api_key = env::var(\"API_KEY\")?;\n    \
             let key = cache.key_for(&request.path);\n    \
             headers.insert(\"Authorization\", format!(\"Bearer {}\", token.value()));\n    \
             Ok(())\n}\n",
            "export function refresh(session) {\n  if (!session.accessToken) { throw new Error('missing token'); }\n  \
             return fetch(`${API_BASE}/auth/refresh`, { method: 'POST', credentials: 'include' });\n}\n",
            "$ cargo test --workspace\n   Compiling yalper v0.1.0\n    Finished `test` profile in 4.21s\n\
             test store::tests::keys_are_unique ... ok\ntest result: ok. 93 passed; 0 failed\n",
            "They asked for the API docs and the access key rotation policy. Keys must be rotated every \
             90 days, and the secret store keeps the old token for a week.",
            "R\u{e9}sum\u{e9}: na\u{ef}ve caf\u{e9}, \u{6771}\u{4eac}, \u{1f389}, \u{43a}\u{43b}\u{44e}\u{447}.",
        ];
        for text in samples {
            assert_eq!(redact_str(text), None, "changed: {text:?}");
        }
    }

    #[test]
    fn identifier_assignments_are_over_redacted() {
        // gitleaks' generic rule allowlists values made only of letters, `_`, `.` and `-`. Allowlists are
        // not applied (masking a harmless value is better than leaking a secret), so code that assigns a
        // keyword-named variable from a varied enough identifier is masked. Snapshots keep the real code.
        assert_eq!(
            redacted("const apiKey = process.env.API_KEY;"),
            "const apiKey = [REDACTED:generic-api-key];"
        );
    }

    #[test]
    fn non_ascii_text_around_a_secret_is_kept() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 22));
        let text = format!("cl\u{e9}: \u{ab}{github}\u{bb} \u{6771}\u{4eac}\u{1f389}");
        assert_eq!(
            redacted(&text),
            "cl\u{e9}: \u{ab}[REDACTED:github-pat]\u{bb} \u{6771}\u{4eac}\u{1f389}"
        );
    }

    #[test]
    fn overlapping_matches_become_one_marker() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 23));
        let result = redacted(&format!("GITHUB_TOKEN={github}\n"));
        assert_eq!(result.matches("[REDACTED:").count(), 1, "{result}");
        assert!(
            result.starts_with("GITHUB_TOKEN=[REDACTED:") && result.ends_with("]\n"),
            "{result}"
        );
    }

    #[test]
    fn long_strings_are_cut_with_their_length() {
        let text = "x".repeat(MAX_STRING_BYTES + 10);
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}[TRUNCATED: {} bytes in total]",
                "x".repeat(MAX_STRING_BYTES),
                text.len()
            )
        );

        // A cut inside a multi-byte character moves back to the character's start.
        let text = format!(
            "{}\u{e9}{}",
            "x".repeat(MAX_STRING_BYTES - 1),
            "y".repeat(10)
        );
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}{}",
                "x".repeat(MAX_STRING_BYTES - 1),
                truncation_marker(text.len())
            )
        );
    }

    #[test]
    fn a_secret_across_the_cut_leaves_no_prefix() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 24));
        let mut text = "x ".repeat((MAX_STRING_BYTES - 10) / 2);
        text.push_str(&github);
        text.push_str(&" y".repeat(1000));
        let result = redact_str(&text).unwrap();
        assert!(
            !result.contains("ghp_"),
            "secret prefix left before the cut"
        );
        assert!(result.ends_with(&format!(
            "[REDACTED:github-pat]{}",
            truncation_marker(text.len())
        )));
    }

    #[test]
    fn a_secret_only_after_the_cut_is_dropped() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 25));
        let text = format!("{}{github}", "x".repeat(MAX_STRING_BYTES + 100));
        let result = redact_str(&text).unwrap();
        assert!(!result.contains("ghp_") && !result.contains("REDACTED"));
    }

    #[test]
    fn a_json_value_is_cut_to_its_budget() {
        let big = "z".repeat(MAX_STRING_BYTES);
        let mut value = json!({ "parts": [big, big, big, big, big, "short", ""] });
        redact_json(&mut value);
        let parts: Vec<&str> = value["parts"]
            .as_array()
            .unwrap()
            .iter()
            .map(|part| part.as_str().unwrap())
            .collect();
        let kept: usize = parts.iter().map(|part| part.matches('z').count()).sum();
        assert!(kept <= MAX_JSON_TEXT_BYTES, "{kept} bytes kept");
        assert_eq!(parts[0], big);
        assert!(parts[3].ends_with(&truncation_marker(MAX_STRING_BYTES)));
        assert_eq!(parts[4], truncation_marker(MAX_STRING_BYTES));
        assert_eq!(parts[5], truncation_marker(5));
        assert_eq!(parts[6], "");
    }

    #[test]
    fn tiny_strings_use_up_the_budget_too() {
        let count = MAX_JSON_TEXT_BYTES / STRING_COST_BYTES + 10;
        let mut value = Value::Array(vec![Value::from("ey"); count]);
        redact_json(&mut value);
        let items = value.as_array().unwrap();
        assert_eq!(items[0], "ey");
        assert_eq!(items[count - 1], truncation_marker(2));
    }

    #[test]
    fn shannon_entropy_in_bits_per_byte() {
        assert_eq!(shannon_entropy(b"aaaa"), 0.0);
        assert_eq!(shannon_entropy(b"aabb"), 1.0);
        assert_eq!(shannon_entropy(b"abcdefgh"), 3.0);
    }
}
