//! Secret redaction: masks API keys, tokens, passwords, and similar secrets in hook payloads before anything
//! is written to disk.
//!
//! The rules are gitleaks' (v8.30.1, MIT, see `third_party/gitleaks/`) plus a few of Yalper's own
//! (`rules/yalper.toml`), turned into a static table by `build.rs`. A hook runs in a new process every
//! time, so compiling all the regexes up front (about 50 ms) is not an option. Instead, one
//! case-insensitive pass over the text finds which rule keywords occur, and only the rules with a keyword
//! hit are compiled (once per process) and run. Text with no keyword costs a single substring scan.
//!
//! A match's secret is the rule's secret group, else the first non-empty group, else the whole match. The
//! match is kept when that secret's Shannon entropy is at or above the rule's threshold and, for the rules
//! that have gitleaks' letters-only allowlist, when the secret is not made only of letters, `_`, `.` and
//! `-`. No other allowlists or stopwords are applied: masking a harmless value is better than writing a
//! real secret to disk. The secret is replaced with `[REDACTED:<rule-id>]`, or the whole match when the
//! rule has several groups and no secret group (those groups are classifiers or fragments, not the secret).
//!
//! Besides each string on its own, Yalper also scans an object entry's key with its string value, as
//! `"key": "value"` (so `{"password": "..."}` is caught), and, when a string contains `\"`, the string
//! with `\"` and `\\` unescaped (JSON escaped twice, as in logs).

use std::cmp::Reverse;
use std::fmt::Write as _;
use std::sync::OnceLock;
use std::time::{Duration, Instant};

use aho_corasick::AhoCorasick;
use regex_automata::meta::{self, Regex};
use regex_automata::util::syntax;
use serde_json::Value;

/// Longer strings are cut to this many bytes and end with `[TRUNCATED: <original length> bytes in total]`.
pub const MAX_STRING_BYTES: usize = 256 * 1024;

/// The most text one [`redact_json`] call keeps. Once it is used up, every further string is replaced by
/// its truncation marker. Real payloads rarely come close.
pub const MAX_JSON_TEXT_BYTES: usize = 1024 * 1024;

/// How long one [`redact_json`] or [`redact_str`] call may take. Its cost is the text's size times the
/// number of rules whose keywords occur, and hostile text (a file the agent reads, a command's output) can
/// contain every keyword: up to about 0.7 s for one 256 KiB string and 1.4 s for a payload were measured.
/// The deadline is checked before each rule runs; once it has passed, the current string and every later
/// one are replaced by their truncation marker, never written raw. So a hostile payload costs about 50 ms
/// (plus at most one rule run), and normal payloads take a few milliseconds.
pub const DEADLINE: Duration = Duration::from_millis(50);

/// What each string costs from [`MAX_JSON_TEXT_BYTES`] on top of its length: the fixed work of scanning
/// one string, so that a payload of millions of tiny strings is bounded too.
const STRING_COST_BYTES: usize = 64;

/// How far past the cut a long string is still scanned, so a secret that straddles the cut is masked
/// instead of leaving its first bytes behind. Larger than any realistic secret, including a PEM private
/// key block.
const CUT_OVERLAP_BYTES: usize = 16 * 1024;

/// How much of a key and of its string value are scanned together. A rule that needs the key (such as
/// `generic-api-key` on `{"password": "..."}`) finds the secret near the start of the value.
const PAIR_KEY_BYTES: usize = 1024;
const PAIR_VALUE_BYTES: usize = 1024;

/// One rule, as generated by `build.rs`.
struct Rule {
    id: &'static str,
    regex: &'static str,
    /// The capture group holding the secret, or 0 to use the first non-empty group (or the whole match).
    secret_group: usize,
    /// Minimum Shannon entropy of the secret, in bits per byte; 0 means no check.
    entropy: f64,
    /// gitleaks' allowlist `^[a-zA-Z_.-]+$`: a secret made only of these is a plain identifier.
    letters_only_allowlist: bool,
}

// Defines `RULE_COUNT`, `RULES`, `KEYWORDS` (lowercase, sorted) and `KEYWORD_RULES` (for each keyword,
// the indexes of the rules that list it).
include!(concat!(env!("OUT_DIR"), "/rules.rs"));

/// Redacts every string in `value`, object keys included, in place. In each object, keys come first, then
/// string values from the shortest, then nested arrays and objects, so short metadata is not lost when the
/// budget or the deadline runs out. Each string is cut to [`MAX_STRING_BYTES`] and the whole value to
/// [`MAX_JSON_TEXT_BYTES`]; the call stops scanning at [`DEADLINE`].
pub fn redact_json(value: &mut Value) {
    redact_json_until(value, Instant::now() + deadline());
}

/// `text` with its secrets masked and cut to [`MAX_STRING_BYTES`], or `None` when it is unchanged. Becomes
/// a truncation marker if scanning takes longer than [`DEADLINE`].
pub fn redact_str(text: &str) -> Option<String> {
    let mut pass = Pass::new(Instant::now() + deadline());
    redact_string(text, None, &mut pass)
}

/// [`DEADLINE`], except in this module's unit tests, which run unoptimized and in parallel; the tests of the
/// deadline itself set their own.
fn deadline() -> Duration {
    if cfg!(test) {
        Duration::from_secs(60)
    } else {
        DEADLINE
    }
}

fn redact_json_until(value: &mut Value, deadline: Instant) {
    redact_value(value, &mut Pass::new(deadline));
}

/// The limits of one redaction call.
struct Pass {
    /// Bytes of text that may still be kept.
    budget: usize,
    deadline: Instant,
    /// Set once the deadline has passed: every later string becomes a truncation marker.
    expired: bool,
}

impl Pass {
    fn new(deadline: Instant) -> Self {
        Self {
            budget: MAX_JSON_TEXT_BYTES,
            deadline,
            expired: false,
        }
    }
}

/// The deadline passed during a scan.
struct Expired;

/// Appended to a string that was cut, with the original length so the record shows how much was dropped.
fn truncation_marker(original_bytes: usize) -> String {
    format!("[TRUNCATED: {original_bytes} bytes in total]")
}

fn redact_value(value: &mut Value, pass: &mut Pass) {
    match value {
        Value::String(text) => {
            if let Some(redacted) = redact_string(text, None, pass) {
                *text = redacted;
            }
        }
        Value::Array(items) => items.iter_mut().for_each(|item| redact_value(item, pass)),
        Value::Object(map) => {
            let mut entries: Vec<(String, Value)> = std::mem::take(map).into_iter().collect();
            let keys: Vec<Option<String>> = entries
                .iter()
                .map(|(key, _)| redact_string(key, None, pass))
                .collect();
            // Short strings first, so metadata survives when a long value uses up the budget or the time.
            let mut strings: Vec<usize> = (0..entries.len())
                .filter(|&index| entries[index].1.is_string())
                .collect();
            strings.sort_by_key(|&index| entries[index].1.as_str().map_or(0, str::len));
            for index in strings {
                let (key, item) = &mut entries[index];
                if let Value::String(text) = item
                    && let Some(redacted) = redact_string(text, Some(key), pass)
                {
                    *text = redacted;
                }
            }
            for (_, item) in &mut entries {
                if matches!(item, Value::Array(_) | Value::Object(_)) {
                    redact_value(item, pass);
                }
            }
            // If two keys became equal (after redaction, or as markers), the later entry replaces the
            // earlier one.
            for ((key, item), redacted) in entries.into_iter().zip(keys) {
                map.insert(redacted.unwrap_or(key), item);
            }
        }
        Value::Null | Value::Bool(_) | Value::Number(_) => {}
    }
}

/// `text` (with `key` when it is that key's value) cut to what is left of the budget, with its secrets
/// masked, or `None` when it is unchanged. Charges the budget.
fn redact_string(text: &str, key: Option<&str>, pass: &mut Pass) -> Option<String> {
    if text.is_empty() {
        return None;
    }
    if pass.expired {
        return Some(truncation_marker(text.len()));
    }
    let limit = pass.budget.min(MAX_STRING_BYTES);
    pass.budget = pass
        .budget
        .saturating_sub(text.len().min(limit) + STRING_COST_BYTES);

    let keep_end = floor_char_boundary(text, limit);
    let scan_end = if keep_end == 0 {
        0
    } else {
        floor_char_boundary(text, limit + CUT_OVERLAP_BYTES)
    };
    let secrets = match string_secrets(&text[..scan_end], key, pass.deadline) {
        Ok(secrets) => secrets,
        Err(Expired) => {
            pass.expired = true;
            return Some(truncation_marker(text.len()));
        }
    };
    if secrets.is_empty() && keep_end == text.len() {
        return None;
    }

    let mut redacted = String::with_capacity(keep_end + 64);
    let mut position = 0;
    for secret in secrets.iter().take_while(|secret| secret.start < keep_end) {
        redacted.push_str(&text[position..secret.start]);
        write!(redacted, "[REDACTED:{}]", RULES[secret.rule].id).unwrap();
        position = secret.end;
    }
    if position < keep_end {
        redacted.push_str(&text[position..keep_end]);
    }
    if keep_end < text.len() {
        redacted.push_str(&truncation_marker(text.len()));
    }
    Some(redacted)
}

/// A byte range of the text to mask, and the rule that found it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Secret {
    start: usize,
    end: usize,
    rule: usize,
}

/// The secrets of a string, on its character boundaries, sorted and merged so that no two overlap: found
/// in the string itself, in it with `\"` and `\\` unescaped, and with the key it is the value of.
fn string_secrets(
    text: &str,
    key: Option<&str>,
    deadline: Instant,
) -> Result<Vec<Secret>, Expired> {
    let mut secrets = find_secrets(text, deadline)?;

    if text.contains("\\\"") {
        let (unescaped, offsets) = unescape_quotes(text);
        for secret in find_secrets(&unescaped, deadline)? {
            secrets.push(Secret {
                start: offsets[secret.start],
                end: offsets[secret.end],
                ..secret
            });
        }
    }

    if let Some(key) = key {
        let key = &key[ceil_char_boundary(key, key.len().saturating_sub(PAIR_KEY_BYTES))..];
        let value_end = floor_char_boundary(text, PAIR_VALUE_BYTES);
        let mut pair = format!("\"{key}\": \"{}", &text[..value_end]);
        if value_end == text.len() {
            pair.push('"');
        }
        let value_start = key.len() + 5;
        for secret in find_secrets(&pair, deadline)? {
            let start = secret.start.max(value_start) - value_start;
            let end = secret.end.saturating_sub(value_start).min(value_end);
            if start < end {
                secrets.push(Secret {
                    start,
                    end,
                    ..secret
                });
            }
        }
    }

    for secret in &mut secrets {
        secret.start = floor_char_boundary(text, secret.start);
        secret.end = ceil_char_boundary(text, secret.end);
    }
    secrets.sort_unstable_by_key(|secret| (secret.start, Reverse(secret.end), secret.rule));
    let mut merged: Vec<Secret> = Vec::with_capacity(secrets.len());
    for secret in secrets {
        match merged.last_mut() {
            Some(last) if secret.start < last.end => last.end = last.end.max(secret.end),
            _ => merged.push(secret),
        }
    }
    Ok(merged)
}

/// `text` with `\"` and `\\` unescaped, and for each byte of the result, plus its end, the offset of that
/// byte in `text`.
fn unescape_quotes(text: &str) -> (String, Vec<usize>) {
    let bytes = text.as_bytes();
    let mut unescaped = Vec::with_capacity(bytes.len());
    let mut offsets = Vec::with_capacity(bytes.len() + 1);
    let mut index = 0;
    while index < bytes.len() {
        // An escape pair maps to its backslash, so a secret that ends before `\"` ends before the `\`.
        offsets.push(index);
        if bytes[index] == b'\\' && matches!(bytes.get(index + 1), Some(b'"' | b'\\')) {
            index += 1;
        }
        unescaped.push(bytes[index]);
        index += 1;
    }
    offsets.push(bytes.len());
    // Only ASCII backslashes were removed, so the result is still UTF-8.
    let unescaped = String::from_utf8(unescaped).expect("removing ASCII bytes keeps UTF-8 valid");
    (unescaped, offsets)
}

/// The secrets the rules find in `text` (unsorted, may overlap), or `Expired` if the deadline passes
/// before a rule runs.
fn find_secrets(text: &str, deadline: Instant) -> Result<Vec<Secret>, Expired> {
    if Instant::now() >= deadline {
        return Err(Expired);
    }
    let mut candidates = [false; RULE_COUNT];
    let mut any = false;
    for hit in keyword_finder().find_overlapping_iter(text) {
        for &rule in KEYWORD_RULES[hit.pattern().as_usize()] {
            candidates[usize::from(rule)] = true;
            any = true;
        }
    }
    if !any {
        return Ok(Vec::new());
    }

    let bytes = text.as_bytes();
    let mut secrets = Vec::new();
    for (index, rule) in RULES.iter().enumerate() {
        if !candidates[index] {
            continue;
        }
        if Instant::now() >= deadline {
            return Err(Expired);
        }
        let Some(regex) = compiled(index) else {
            continue;
        };
        for captures in regex.captures_iter(bytes) {
            let Some(secret) = (if rule.secret_group > 0 {
                captures.get_group(rule.secret_group)
            } else {
                (1..captures.group_len())
                    .filter_map(|group| captures.get_group(group))
                    .find(|group| !group.is_empty())
                    .or_else(|| captures.get_group(0))
            }) else {
                continue;
            };
            let secret_bytes = &bytes[secret.range()];
            // gitleaks drops a match at or below the threshold; keeping the equal case masks slightly more.
            if secret.is_empty()
                || (rule.entropy > 0.0 && shannon_entropy(secret_bytes) < rule.entropy)
                || (rule.letters_only_allowlist && is_letters_only(secret_bytes))
            {
                continue;
            }
            let masked = if masks_whole_match(rule, captures.group_len()) {
                captures.get_group(0).unwrap_or(secret)
            } else {
                secret
            };
            secrets.push(Secret {
                start: masked.start,
                end: masked.end,
                rule: index,
            });
        }
    }
    Ok(secrets)
}

/// Whether a match of `rule`, whose regex has `group_len` groups counting the whole match, is masked
/// whole. Without a secret group, gitleaks reports the first non-empty group; when a rule has several,
/// they are classifiers or fragments (`jwt-base64` captures the header type, `microsoft-teams-webhook` a
/// 5-character piece), so masking only that group would write most of the secret raw.
fn masks_whole_match(rule: &Rule, group_len: usize) -> bool {
    rule.secret_group == 0 && group_len > 2
}

/// gitleaks' `^[a-zA-Z_.-]+$`.
fn is_letters_only(secret: &[u8]) -> bool {
    secret
        .iter()
        .all(|&byte| byte.is_ascii_alphabetic() || matches!(byte, b'_' | b'.' | b'-'))
}

/// The automaton over all rule keywords, built on first use.
fn keyword_finder() -> &'static AhoCorasick {
    static FINDER: OnceLock<AhoCorasick> = OnceLock::new();
    FINDER.get_or_init(|| {
        AhoCorasick::builder()
            .ascii_case_insensitive(true)
            .build(KEYWORDS)
            .expect("the rule keywords form a valid automaton")
    })
}

/// Rule `index`'s regex, compiled on first use. `None` if it does not compile (a test checks they all do).
fn compiled(index: usize) -> Option<&'static Regex> {
    static COMPILED: [OnceLock<Option<Regex>>; RULE_COUNT] =
        [const { OnceLock::new() }; RULE_COUNT];
    COMPILED[index]
        .get_or_init(|| build_regex(RULES[index].regex).ok())
        .as_ref()
}

/// Compiles a rule's regex with the engine behind the `regex` crate, configured like `regex::bytes`.
///
/// Go's RE2, which gitleaks uses, treats `\w`, `\s`, `\b` and `(?i)` as ASCII, so Unicode mode is off:
/// that is both the faithful port and about 90 times faster to compile. The one-pass DFA is off, since
/// captures only run on the span of a match. The literal prefilter is off for the rules built from
/// gitleaks' semi-generic template, `[\w.-]{0,50}?` before a keyword (101 gitleaks rules, among them
/// `generic-api-key`, which nearly every payload triggers, plus `yalper-password-assignment`): it more
/// than doubles their compile time and does not speed up their search (measured). For the other rules it
/// is cheap and makes the search much faster.
fn build_regex(pattern: &str) -> Result<Regex, Box<meta::BuildError>> {
    let semi_generic = pattern.contains(r"[\w.-]{0,50}?");
    meta::Builder::new()
        .configure(
            meta::Config::new()
                .utf8_empty(false)
                .onepass(false)
                .auto_prefilter(!semi_generic),
        )
        .syntax(syntax::Config::new().unicode(false).utf8(false))
        .build(pattern)
        .map_err(Box::new)
}

/// Shannon entropy in bits per byte. gitleaks counts characters instead; secrets are ASCII, where both agree.
fn shannon_entropy(bytes: &[u8]) -> f64 {
    let mut counts = [0u32; 256];
    for &byte in bytes {
        counts[usize::from(byte)] += 1;
    }
    let length = bytes.len() as f64;
    counts
        .iter()
        .filter(|&&count| count > 0)
        .map(|&count| {
            let frequency = f64::from(count) / length;
            -frequency * frequency.log2()
        })
        .sum()
}

fn floor_char_boundary(text: &str, mut index: usize) -> usize {
    if index >= text.len() {
        return text.len();
    }
    while !text.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn ceil_char_boundary(text: &str, mut index: usize) -> usize {
    while !text.is_char_boundary(index) {
        index += 1;
    }
    index
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    const ALNUM: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    const UPPER_BASE32: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
    const DIGITS: &[u8] = b"0123456789";

    /// A deterministic random-looking string. Fake secrets are built at run time from a prefix and this, so
    /// no complete token appears in the source.
    fn fake(alphabet: &[u8], length: usize, seed: u64) -> String {
        let mut state = seed;
        (0..length)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                char::from(alphabet[(state >> 33) as usize % alphabet.len()])
            })
            .collect()
    }

    fn redacted(text: &str) -> String {
        redact_str(text).unwrap_or_else(|| text.to_owned())
    }

    /// Asserts that `secret` is gone from the redacted `text`, replaced by `rule`'s marker, and returns the
    /// redacted text.
    #[track_caller]
    fn assert_masked(text: &str, secret: &str, rule: &str) -> String {
        let result = redacted(text);
        assert!(!result.contains(secret), "secret left in {result:?}");
        assert!(
            result.contains(&format!("[REDACTED:{rule}]")),
            "no {rule} marker in {result:?}"
        );
        result
    }

    fn group_len(rule: &Rule) -> usize {
        build_regex(rule.regex)
            .unwrap_or_else(|error| panic!("rule {} does not compile: {error}", rule.id))
            .group_info()
            .group_len(regex_automata::PatternID::ZERO)
    }

    #[test]
    fn every_rule_compiles_without_unicode() {
        let gitleaks = RULES.iter().filter(|rule| !rule.id.starts_with("yalper-"));
        assert_eq!(
            gitleaks.count(),
            221,
            "gitleaks v8.30.1 has 221 regex rules"
        );
        for rule in &RULES {
            assert!(
                rule.secret_group < group_len(rule),
                "rule {}: secret group {} does not exist",
                rule.id,
                rule.secret_group
            );
        }
    }

    #[test]
    fn rules_with_several_groups_and_no_secret_group_mask_the_whole_match() {
        let mut whole = Vec::new();
        for rule in &RULES {
            let groups = group_len(rule);
            if masks_whole_match(rule, groups) {
                assert!(rule.secret_group == 0 && groups > 2, "{}", rule.id);
                whole.push(rule.id);
            } else {
                // A rule masks its secret group, its only group, or (no group) the whole match.
                assert!(rule.secret_group > 0 || groups <= 2, "{}", rule.id);
            }
        }
        for id in [
            "jwt-base64",
            "microsoft-teams-webhook",
            "kubernetes-secret-yaml",
        ] {
            assert!(whole.contains(&id), "{id} not in {whole:?}");
        }
    }

    #[test]
    fn letters_only_allowlist_is_on_generic_api_key_only_among_gitleaks_rules() {
        let allowlisted: Vec<&str> = RULES
            .iter()
            .filter(|rule| rule.letters_only_allowlist)
            .map(|rule| rule.id)
            .collect();
        assert_eq!(
            allowlisted,
            [
                "generic-api-key",
                "yalper-password-assignment",
                "yalper-bearer-token"
            ]
        );
    }

    #[test]
    fn every_rule_is_reachable_through_a_lowercase_keyword() {
        let mut reachable = [false; RULE_COUNT];
        for (keyword, rules) in KEYWORDS.iter().zip(KEYWORD_RULES) {
            assert_eq!(*keyword, keyword.to_ascii_lowercase());
            for &rule in rules {
                reachable[usize::from(rule)] = true;
            }
        }
        assert!(reachable.iter().all(|&reachable| reachable));
    }

    #[test]
    fn cloud_provider_access_keys() {
        let aws = format!("AKIA{}", fake(UPPER_BASE32, 16, 1));
        let text = format!("[default]\naws_access_key_id={aws}\nregion=eu-west-3\n");
        let result = redacted(&text);
        assert!(!result.contains(&aws), "{result:?}");
        assert!(result.ends_with("]\nregion=eu-west-3\n"), "{result:?}");
        assert_masked(&format!("id {aws} in use"), &aws, "aws-access-token");

        let gcp = format!("AIza{}", fake(ALNUM, 35, 2));
        assert_masked(&format!("maps.load('{gcp}')"), &gcp, "gcp-api-key");
    }

    #[test]
    fn github_tokens() {
        let classic = format!("ghp_{}", fake(ALNUM, 36, 3));
        let result = assert_masked(
            &format!("git clone https://{classic}@github.com/o/r"),
            &classic,
            "github-pat",
        );
        assert_eq!(
            result,
            "git clone https://[REDACTED:github-pat]@github.com/o/r"
        );

        let fine_grained = format!("github_pat_{}", fake(ALNUM, 82, 4));
        assert_masked(
            &format!("use {fine_grained} here"),
            &fine_grained,
            "github-fine-grained-pat",
        );
    }

    #[test]
    fn llm_provider_api_keys() {
        let anthropic = format!("sk-ant-api03-{}AA", fake(ALNUM, 93, 5));
        assert_masked(
            &format!("client = Client('{anthropic}')"),
            &anthropic,
            "anthropic-api-key",
        );

        let openai = format!(
            "sk-proj-{}T3BlbkFJ{}",
            fake(ALNUM, 74, 6),
            fake(ALNUM, 74, 7)
        );
        assert_masked(
            &format!("OPENAI_API_KEY={openai}\n"),
            &openai,
            "openai-api-key",
        );

        let huggingface = format!(
            "hf_{}",
            fake(b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJ", 34, 8)
        );
        assert_masked(
            &format!("login {huggingface}\n"),
            &huggingface,
            "huggingface-access-token",
        );
    }

    #[test]
    fn slack_tokens() {
        let bot = format!(
            "xoxb-{}-{}-{}",
            fake(DIGITS, 12, 9),
            fake(DIGITS, 13, 10),
            fake(ALNUM, 24, 11)
        );
        assert_masked(&format!("SLACK={bot} ./post.sh"), &bot, "slack-bot-token");

        let webhook = format!("https://hooks.slack.com/services/{}", fake(ALNUM, 44, 12));
        assert_masked(
            &format!("curl -X POST {webhook}"),
            &webhook,
            "slack-webhook-url",
        );
    }

    #[test]
    fn private_key_block() {
        let body: Vec<String> = (0..12).map(|line| fake(ALNUM, 64, 100 + line)).collect();
        let block = format!(
            "-----BEGIN {kind} KEY-----\n{body}\n-----END {kind} KEY-----",
            kind = "RSA PRIVATE",
            body = body.join("\n")
        );
        let result = assert_masked(
            &format!("cat id_rsa\n{block}\ndone"),
            &body[5],
            "private-key",
        );
        assert_eq!(result, "cat id_rsa\n[REDACTED:private-key]\ndone");
    }

    #[test]
    fn json_web_token() {
        let jwt = format!(
            "eyJ{}.eyJ{}.{}",
            fake(ALNUM, 33, 13),
            fake(ALNUM, 60, 14),
            fake(ALNUM, 43, 15)
        );
        assert_masked(&format!("Cookie: session={jwt}; Path=/"), &jwt, "jwt");
    }

    #[test]
    fn generic_assignments() {
        let password = fake(ALNUM, 20, 16);
        let result = assert_masked(
            &format!("password={password}"),
            &password,
            "generic-api-key",
        );
        assert_eq!(result, "password=[REDACTED:generic-api-key]");

        let api_key = fake(ALNUM, 32, 17);
        let result = assert_masked(
            &format!("export API_KEY=\"{api_key}\"\n"),
            &api_key,
            "generic-api-key",
        );
        assert_eq!(result, "export API_KEY=\"[REDACTED:generic-api-key]\"\n");

        let secret = fake(ALNUM, 40, 18);
        assert_masked(
            &format!("{{\"client_secret\": \"{secret}\"}}"),
            &secret,
            "generic-api-key",
        );
    }

    #[test]
    fn low_entropy_values_are_kept() {
        // Below the generic rule's 3.5 bits per byte, as in gitleaks.
        for text in ["password=aaaaaaaaaaaaaaaa", "api_key = 1111111111222222"] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn secrets_inside_tool_input_and_tool_response() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 19));
        let password = fake(ALNUM, 24, 20);
        let mut payload = json!({
            "session_id": "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71",
            "hook_event_name": "PostToolUse",
            "tool_name": "Bash",
            "tool_input": {
                "command": format!("GH_TOKEN={github} gh pr list"),
                "env": { "nested": [1, true, null, { "deeper": format!("using {github}") }] },
            },
            "tool_response": {
                "stdout": format!("connecting with db_password: {password}\nok\n"),
                "stderr": "",
                "interrupted": false,
            },
        });
        redact_json(&mut payload);
        let text = payload.to_string();
        assert!(
            !text.contains(&github) && !text.contains(&password),
            "{text}"
        );
        assert_eq!(
            payload["tool_input"]["env"]["nested"][3]["deeper"],
            "using [REDACTED:github-pat]"
        );
        assert_eq!(
            payload["tool_response"]["stdout"],
            "connecting with db_password: [REDACTED:generic-api-key]\nok\n"
        );
        assert_eq!(
            payload["session_id"],
            "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71"
        );
        assert_eq!(payload["tool_input"]["env"]["nested"][0], 1);
        assert_eq!(payload["tool_response"]["interrupted"], false);
    }

    #[test]
    fn object_keys_are_redacted_in_place() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 21));
        let mut value = json!({ "a": 1, format!("token {github}"): 2, "z": 3 });
        redact_json(&mut value);
        let keys: Vec<&String> = value.as_object().unwrap().keys().collect();
        assert_eq!(keys.len(), 3);
        assert!(keys.iter().all(|key| !key.contains(&github)), "{keys:?}");
        assert_eq!(value["token [REDACTED:github-pat]"], 2);
    }

    #[test]
    fn git_shas_uuids_code_and_prose_are_unchanged() {
        let samples = [
            "commit 9fceb02d0ae598e95dc970b74767f19372d61af8\nAuthor: Dev <dev@example.com>\n\n    Fix parser\n",
            "3f786850e387550fdab836ed7e6dc881de23001b a1b2c3d HEAD@{0}: checkout: moving from main to fix",
            "session 4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71 resumed (request 0d9e3c3a-12f4-4bb1-9d0e-8f6f2a0c5b7e)",
            "fn verify(password: &str, hash: &PasswordHash) -> Result<(), Error> {\n    \
             let token = tokens.next().ok_or(Error::MissingToken)?;\n    \
             let api_key = env::var(\"API_KEY\")?;\n    \
             let key = cache.key_for(&request.path);\n    \
             headers.insert(\"Authorization\", format!(\"Bearer {}\", token.value()));\n    \
             Ok(())\n}\n",
            "export function refresh(session) {\n  if (!session.accessToken) { throw new Error('missing token'); }\n  \
             return fetch(`${API_BASE}/auth/refresh`, { method: 'POST', credentials: 'include' });\n}\n",
            "$ cargo test --workspace\n   Compiling yalper v0.1.0\n    Finished `test` profile in 4.21s\n\
             test store::tests::keys_are_unique ... ok\ntest result: ok. 93 passed; 0 failed\n",
            "They asked for the API docs and the access key rotation policy. Keys must be rotated every \
             90 days, and the secret store keeps the old token for a week.",
            "R\u{e9}sum\u{e9}: na\u{ef}ve caf\u{e9}, \u{6771}\u{4eac}, \u{1f389}, \u{43a}\u{43b}\u{44e}\u{447}.",
        ];
        for text in samples {
            assert_eq!(redact_str(text), None, "changed: {text:?}");
        }
    }

    #[test]
    fn identifier_assignments_are_kept_but_values_with_digits_are_masked() {
        // gitleaks' letters-only allowlist on generic-api-key.
        for text in [
            "const apiKey = process.env.API_KEY;",
            "const secretName = config.secretName;",
            "token = response.access_token_value",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
        let value = format!("process.env.{}", fake(ALNUM, 12, 30));
        let result = assert_masked(
            &format!("const apiKey = {value};"),
            &value,
            "generic-api-key",
        );
        assert_eq!(result, "const apiKey = [REDACTED:generic-api-key];");
    }

    #[test]
    fn jwt_in_base64_is_masked_whole() {
        // `ZXlK` + `aGJHY2lPaU` is `{"alg":` base64-encoded twice; the rule's groups only name the header.
        let token = format!("ZXlKaGJHY2lPaU{}", fake(ALNUM, 120, 31));
        let result = assert_masked(&format!("seen {token} (expired)"), &token, "jwt-base64");
        assert_eq!(result, "seen [REDACTED:jwt-base64] (expired)");
    }

    #[test]
    fn teams_webhook_is_masked_whole() {
        let hex = |length, seed| fake(b"0123456789abcdef", length, seed);
        let guid = |seed: u64| {
            format!(
                "{}-{}-{}-{}-{}",
                hex(8, seed),
                hex(4, seed + 1),
                hex(4, seed + 2),
                hex(4, seed + 3),
                hex(12, seed + 4)
            )
        };
        let webhook = format!(
            "https://contoso.webhook.office.com/webhookb2/{}@{}/IncomingWebhook/{}/{}",
            guid(40),
            guid(50),
            hex(32, 60),
            guid(70)
        );
        let result = assert_masked(
            &format!("curl {webhook} -d @msg.json"),
            &webhook[60..],
            "microsoft-teams-webhook",
        );
        assert_eq!(
            result,
            "curl [REDACTED:microsoft-teams-webhook] -d @msg.json"
        );
    }

    #[test]
    fn sonar_token_uses_the_secret_group() {
        let token = format!("squ_{}", fake(b"0123456789abcdef", 40, 32));
        let result = assert_masked(&format!("sonar.login={token}\n"), &token, "sonar-api-token");
        assert_eq!(result, "sonar.login=[REDACTED:sonar-api-token]\n");
    }

    #[test]
    fn a_key_and_its_value_are_scanned_together() {
        let password = fake(ALNUM, 18, 33);
        let api_key = fake(ALNUM, 32, 34);
        let bearer = fake(ALNUM, 40, 35);
        let opaque = fake(ALNUM, 30, 36);
        let mut input = json!({
            "server": "db",
            "password": password,
            "options": { "api_key": api_key, "retries": 3 },
            "headers": [{ "Authorization": format!("Bearer {bearer}"), "X-Auth-Token": opaque }],
        });
        redact_json(&mut input);
        let text = input.to_string();
        for secret in [&password, &api_key, &bearer, &opaque] {
            assert!(!text.contains(secret.as_str()), "{secret} left in {text}");
        }
        assert_eq!(input["password"], "[REDACTED:generic-api-key]");
        assert_eq!(input["server"], "db");
        assert_eq!(input["options"]["retries"], 3);
        assert_eq!(
            input["headers"][0]["X-Auth-Token"],
            "[REDACTED:generic-api-key]"
        );
    }

    #[test]
    fn partial_private_key_is_masked_to_the_end() {
        let lines: Vec<String> = (0..6).map(|line| fake(ALNUM, 64, 200 + line)).collect();
        let head = format!(
            "$ head -n 7 id_rsa\n-----BEGIN {} KEY-----\n{}",
            "OPENSSH PRIVATE",
            lines.join("\n")
        );
        let result = redacted(&head);
        assert_eq!(
            result,
            "$ head -n 7 id_rsa\n[REDACTED:yalper-private-key-partial]"
        );

        // Escaped newlines, as in a JSON string inside a log line.
        let escaped = format!(
            "key=\"-----BEGIN {} KEY-----\\n{}\\n\"",
            "EC PRIVATE", lines[0]
        );
        assert_masked(&escaped, &lines[0], "yalper-private-key-partial");

        // Code that only mentions the header is kept.
        let code = "if pem.starts_with(\"-----BEGIN RSA PRIVATE KEY-----\") { return Kind::Rsa; }";
        assert_eq!(redact_str(code), None);
    }

    #[test]
    fn url_passwords_are_masked() {
        for (scheme, user) in [
            ("postgres", "admin"),
            ("mongodb+srv", "app"),
            ("redis", ""),
            ("https", "deploy"),
        ] {
            let password = fake(ALNUM, 14, 37);
            let text = format!("connect {scheme}://{user}:{password}@db.internal:5432/app");
            let result = assert_masked(&text, &password, "yalper-url-password");
            assert_eq!(
                result,
                format!(
                    "connect {scheme}://{user}:[REDACTED:yalper-url-password]@db.internal:5432/app"
                )
            );
        }
        for text in [
            "http://localhost:8080/api/v1?user=a@b",
            "ssh://git@github.com:22/org/repo.git",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn pass_and_pwd_assignments_are_masked() {
        for name in ["DB_PASS", "DB_PWD", "smtp.pass", "MYSQL_ROOT_PWD"] {
            let password = fake(ALNUM, 16, 38);
            let result = assert_masked(
                &format!("{name}={password}\n"),
                &password,
                "yalper-password-assignment",
            );
            assert_eq!(
                result,
                format!("{name}=[REDACTED:yalper-password-assignment]\n")
            );
        }
        for text in [
            "DB_PASS=aaaaaaaaaaaaaaaa",
            "bypass = settings.bypassCache",
            "    pass\n",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn bearer_tokens_are_masked() {
        let token = fake(ALNUM, 32, 39);
        let result = assert_masked(
            &format!("GET /v1/me HTTP/1.1\nAuthorization: Bearer {token}\nAccept: */*\n"),
            &token,
            "yalper-bearer-token",
        );
        assert_eq!(
            result,
            "GET /v1/me HTTP/1.1\nAuthorization: Bearer [REDACTED:yalper-bearer-token]\nAccept: */*\n"
        );
        assert_eq!(redact_str("Use Bearer authentication for the API."), None);
        // In a curl command, gitleaks' curl-auth-header rule masks the whole header.
        let curl = format!("curl -H 'Authorization: Bearer {token}' https://api.example.com");
        assert!(!redacted(&curl).contains(&token));
    }

    #[test]
    fn json_escaped_twice_is_scanned_unescaped() {
        let secret = fake(ALNUM, 24, 40);
        let line = format!("{{\"log\": \"{{\\\"client_secret\\\": \\\"{secret}\\\"}}\"}}");
        let result = assert_masked(&line, &secret, "generic-api-key");
        assert_eq!(
            result,
            "{\"log\": \"{\\\"client_secret\\\": \\\"[REDACTED:generic-api-key]\\\"}\"}"
        );
    }

    #[test]
    fn metadata_survives_a_payload_over_the_budget() {
        let content = "line of the new file\n".repeat(MAX_STRING_BYTES / 20);
        let original = "line of the old file\n".repeat(MAX_STRING_BYTES / 20);
        let patch: Vec<Value> = (0..2000)
            .map(|line| json!({ "oldStart": line, "lines": [format!("-old {line}"), format!("+new {line}")] }))
            .collect();
        let mut payload = json!({
            "session_id": "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71",
            "transcript_path": "/home/dev/.claude/projects/demo/session.jsonl",
            "cwd": "/home/dev/demo",
            "hook_event_name": "PostToolUse",
            "tool_name": "Write",
            "tool_input": { "file_path": "/home/dev/demo/big.txt", "content": content },
            "tool_response": {
                "type": "update",
                "filePath": "/home/dev/demo/big.txt",
                "content": content,
                "originalFile": original,
                "structuredPatch": patch,
            },
            "tool_use_id": "toolu_01ABCDEFGH",
        });
        redact_json(&mut payload);
        assert_eq!(payload["tool_use_id"], "toolu_01ABCDEFGH");
        assert_eq!(payload["tool_name"], "Write");
        assert_eq!(
            payload["transcript_path"],
            "/home/dev/.claude/projects/demo/session.jsonl"
        );
        assert_eq!(payload["tool_response"]["type"], "update");
        assert_eq!(
            payload["tool_response"]["filePath"],
            "/home/dev/demo/big.txt"
        );
        assert_eq!(payload["tool_input"]["file_path"], "/home/dev/demo/big.txt");
        assert_eq!(payload["hook_event_name"], "PostToolUse");
        let structured = payload["tool_response"]["structuredPatch"].to_string();
        assert!(structured.contains("[TRUNCATED: "), "the budget ran out");
    }

    #[test]
    fn after_the_deadline_strings_become_markers() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 41));
        let mut payload = json!({ "a": format!("token {github}"), "bb": ["plain", ""], "ccc": 1 });
        redact_json_until(&mut payload, Instant::now());
        assert_eq!(
            payload,
            json!({
                "[TRUNCATED: 1 bytes in total]": "[TRUNCATED: 46 bytes in total]",
                "[TRUNCATED: 2 bytes in total]": ["[TRUNCATED: 5 bytes in total]", ""],
                "[TRUNCATED: 3 bytes in total]": 1,
            })
        );
    }

    #[test]
    fn hostile_text_stops_at_the_deadline_without_leaking() {
        // Every keyword followed by an assignment, so every rule runs over the whole string.
        let keywords = KEYWORDS.join("_v = \"Zq8Lx3Vn7Rb2Kt9Ws4Pd6\"\n");
        let github = format!("ghp_{}", fake(ALNUM, 36, 42));
        let mut text = keywords.repeat(MAX_STRING_BYTES / keywords.len() + 1);
        text.truncate(MAX_STRING_BYTES - 100);
        text.push_str(&github);
        let mut payload =
            json!({ "tool_response": [text.clone(), text.clone(), text.clone(), text] });
        let start = Instant::now();
        redact_json_until(&mut payload, start + DEADLINE);
        let elapsed = start.elapsed();
        // Debug builds run every rule much slower; the margin covers one rule run past the deadline.
        assert!(elapsed < Duration::from_secs(2), "took {elapsed:?}");
        let output = payload.to_string();
        assert!(!output.contains(&github));
        assert!(output.contains("[TRUNCATED: "));
    }

    #[test]
    fn non_ascii_text_around_a_secret_is_kept() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 22));
        let text = format!("cl\u{e9}: \u{ab}{github}\u{bb} \u{6771}\u{4eac}\u{1f389}");
        assert_eq!(
            redacted(&text),
            "cl\u{e9}: \u{ab}[REDACTED:github-pat]\u{bb} \u{6771}\u{4eac}\u{1f389}"
        );
    }

    #[test]
    fn overlapping_matches_become_one_marker() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 23));
        let result = redacted(&format!("GITHUB_TOKEN={github}\n"));
        assert_eq!(result.matches("[REDACTED:").count(), 1, "{result}");
        assert!(
            result.starts_with("GITHUB_TOKEN=[REDACTED:") && result.ends_with("]\n"),
            "{result}"
        );
    }

    #[test]
    fn long_strings_are_cut_with_their_length() {
        let text = "x".repeat(MAX_STRING_BYTES + 10);
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}[TRUNCATED: {} bytes in total]",
                "x".repeat(MAX_STRING_BYTES),
                text.len()
            )
        );

        // A cut inside a multi-byte character moves back to the character's start.
        let text = format!(
            "{}\u{e9}{}",
            "x".repeat(MAX_STRING_BYTES - 1),
            "y".repeat(10)
        );
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}{}",
                "x".repeat(MAX_STRING_BYTES - 1),
                truncation_marker(text.len())
            )
        );
    }

    #[test]
    fn a_secret_across_the_cut_leaves_no_prefix() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 24));
        let mut text = "x ".repeat((MAX_STRING_BYTES - 10) / 2);
        text.push_str(&github);
        text.push_str(&" y".repeat(1000));
        let result = redact_str(&text).unwrap();
        assert!(
            !result.contains("ghp_"),
            "secret prefix left before the cut"
        );
        assert!(result.ends_with(&format!(
            "[REDACTED:github-pat]{}",
            truncation_marker(text.len())
        )));
    }

    #[test]
    fn a_secret_only_after_the_cut_is_dropped() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 25));
        let text = format!("{}{github}", "x".repeat(MAX_STRING_BYTES + 100));
        let result = redact_str(&text).unwrap();
        assert!(!result.contains("ghp_") && !result.contains("REDACTED"));
    }

    #[test]
    fn a_json_value_is_cut_to_its_budget() {
        let big = "z".repeat(MAX_STRING_BYTES);
        let mut value = json!({ "parts": [big, big, big, big, big, "short", ""] });
        redact_json(&mut value);
        let parts: Vec<&str> = value["parts"]
            .as_array()
            .unwrap()
            .iter()
            .map(|part| part.as_str().unwrap())
            .collect();
        let kept: usize = parts.iter().map(|part| part.matches('z').count()).sum();
        assert!(kept <= MAX_JSON_TEXT_BYTES, "{kept} bytes kept");
        assert_eq!(parts[0], big);
        assert!(parts[3].ends_with(&truncation_marker(MAX_STRING_BYTES)));
        assert_eq!(parts[4], truncation_marker(MAX_STRING_BYTES));
        assert_eq!(parts[5], truncation_marker(5));
        assert_eq!(parts[6], "");
    }

    #[test]
    fn tiny_strings_use_up_the_budget_too() {
        let count = MAX_JSON_TEXT_BYTES / STRING_COST_BYTES + 10;
        let mut value = Value::Array(vec![Value::from("ey"); count]);
        redact_json(&mut value);
        let items = value.as_array().unwrap();
        assert_eq!(items[0], "ey");
        assert_eq!(items[count - 1], truncation_marker(2));
    }

    #[test]
    fn shannon_entropy_in_bits_per_byte() {
        assert_eq!(shannon_entropy(b"aaaa"), 0.0);
        assert_eq!(shannon_entropy(b"aabb"), 1.0);
        assert_eq!(shannon_entropy(b"abcdefgh"), 3.0);
    }
}
