//! Secret redaction: masks API keys, tokens, passwords, and similar secrets in hook payloads before anything
//! is written to disk.
//!
//! The rules are gitleaks' (v8.30.1, MIT, see `third_party/gitleaks/`) plus a few of Yalper's own
//! (`rules/yalper.toml`), turned into a static table by `build.rs`. A hook runs in a new process every
//! time, so compiling all the regexes up front (about 50 ms) is not an option. Instead, one
//! case-insensitive pass over the text finds which rule keywords occur, and only the rules with a keyword
//! hit are compiled (once per process) and run. Text with no keyword costs a single substring scan.
//!
//! A match's secret is the rule's secret group, else the first non-empty group, else the whole match. The
//! match is kept when that secret's Shannon entropy is at or above the rule's threshold and, for the rules
//! that have gitleaks' letters-only allowlist, when the secret is not made only of letters, `_`, `.` and
//! `-`. No other allowlists or stopwords are applied: masking a harmless value is better than writing a
//! real secret to disk. The secret is replaced with `[REDACTED:<rule-id>]`, or the whole match when the
//! rule has several groups and no secret group (those groups are classifiers or fragments, not the secret).
//!
//! Besides each string on its own, Yalper also scans an object entry's key with its string value, as
//! `"key": "value"` (so `{"password": "..."}` is caught), and, when a string contains `\"`, the string
//! with `\"` and `\\` unescaped (JSON escaped twice, as in logs).

use std::cmp::Reverse;
use std::collections::HashMap;
use std::fmt::Write as _;
use std::sync::{OnceLock, mpsc};
use std::thread;
use std::time::{Duration, Instant};

use aho_corasick::AhoCorasick;
use regex_automata::meta::{self, Regex};
use regex_automata::util::syntax;
use serde_json::{Map, Value};

/// Longer strings are cut to this many bytes and end with `[TRUNCATED: <original length> bytes in total]`.
pub const MAX_STRING_BYTES: usize = 256 * 1024;

/// The most text one [`redact_json`] call keeps. Once it is used up, every further string is replaced by
/// its truncation marker. Real payloads rarely come close.
pub const MAX_JSON_TEXT_BYTES: usize = 1024 * 1024;

/// How long one [`redact_json`] or [`redact_str`] call may take in a release build (debug builds allow
/// [`DEBUG_DEADLINE_FACTOR`] times more). Its cost is the text's size times the number of rules whose
/// keywords occur, and hostile text (a file the agent reads, a command's output) can contain every keyword
/// (up to 1.4 s per payload measured), or target one slow rule (one rule run over 256 KiB measured at
/// 0.6 s). So:
/// - from four fifths of the deadline, checked before each rule runs, the current string and every later
///   one are replaced by their truncation marker, and the redaction returns early with what it has done;
/// - a payload with more than 4 KiB of text is redacted on a worker thread. At the deadline, if the worker
///   has not returned (stuck in one rule run), the call returns the payload with every string and key
///   replaced by its truncation marker, and the worker is left to die with the process. Smaller payloads
///   run on the calling thread, where one rule run cannot take much more than 10 ms.
///
/// Either way nothing is written raw. Normal payloads take a few milliseconds.
pub const DEADLINE: Duration = Duration::from_millis(50);

/// Debug builds run the rules many times slower: normal payloads of 100 to 256 KiB take 40 to 60 ms.
pub const DEBUG_DEADLINE_FACTOR: u32 = 40;

/// How long the caller waits for the worker thread at a time, before checking the deadline again.
const WAIT_SLICE: Duration = Duration::from_millis(2);

/// Values with at most this much text are redacted on the calling thread (see `redact_json_bounded`).
const INLINE_TEXT_BYTES: usize = 4 * 1024;

/// What each string costs from [`MAX_JSON_TEXT_BYTES`] on top of its length: the fixed work of scanning
/// one string, so that a payload of millions of tiny strings is bounded too.
const STRING_COST_BYTES: usize = 64;

/// How far past the cut a long string is still scanned, so a secret that straddles the cut is masked
/// instead of leaving its first bytes behind. Larger than any realistic secret, including a PEM private
/// key block.
const CUT_OVERLAP_BYTES: usize = 16 * 1024;

/// How much of a key and of its string value are scanned together. A rule that needs the key (such as
/// `generic-api-key` on `{"password": "..."}`) finds the secret near the start of the value.
const PAIR_KEY_BYTES: usize = 1024;
const PAIR_VALUE_BYTES: usize = 1024;

/// One rule, as generated by `build.rs`.
struct Rule {
    id: &'static str,
    regex: &'static str,
    /// The capture group holding the secret, or 0 to use the first non-empty group (or the whole match).
    secret_group: usize,
    /// Minimum Shannon entropy of the secret, in bits per byte; 0 means no check.
    entropy: f64,
    /// gitleaks' allowlist `^[a-zA-Z_.-]+$`: a secret made only of these is a plain identifier.
    letters_only_allowlist: bool,
    /// A secret that [`looks_like_code`] is not one.
    code_allowlist: bool,
    /// The capture groups are alternatives for the secret (Yalper rules): the first non-empty one is masked.
    alternative_groups: bool,
}

// Defines `RULE_COUNT`, `RULES`, `KEYWORDS` (lowercase, sorted) and `KEYWORD_RULES` (for each keyword,
// the indexes of the rules that list it).
include!(concat!(env!("OUT_DIR"), "/rules.rs"));

/// Redacts every string in `value`, object keys included, in place. In each object, keys come first, then
/// string values from the shortest, then nested arrays and objects, so short metadata is not lost when the
/// budget or the deadline runs out. Each string is cut to [`MAX_STRING_BYTES`] and the whole value to
/// [`MAX_JSON_TEXT_BYTES`]; the call returns within [`DEADLINE`].
pub fn redact_json(value: &mut Value) {
    redact_json_within(value, deadline());
}

/// `text` with its secrets masked and cut to [`MAX_STRING_BYTES`], or `None` when it is unchanged. Becomes
/// a truncation marker if scanning takes longer than [`DEADLINE`].
pub fn redact_str(text: &str) -> Option<String> {
    let mut value = Value::String(text.to_owned());
    redact_json(&mut value);
    match value {
        Value::String(redacted) if redacted != text => Some(redacted),
        _ => None,
    }
}

fn deadline() -> Duration {
    if cfg!(debug_assertions) {
        DEADLINE * DEBUG_DEADLINE_FACTOR
    } else {
        DEADLINE
    }
}

/// Redacts `value` within `limit` (see [`DEADLINE`]).
fn redact_json_within(value: &mut Value, limit: Duration) {
    redact_json_bounded(value, limit * 4 / 5, limit);
}

/// Redacts `value`, stopping the scan after `soft` and returning markers after `hard`.
///
/// Small values run on the calling thread: one rule run over [`INLINE_TEXT_BYTES`] takes at most about
/// 10 ms (2.5 µs per byte for the slowest rule on targeted input), and a worker thread costs 0.4 to 0.7 ms
/// on Windows, more when several calls each warm up the rules' caches on a new thread. Larger values run
/// on a worker thread, abandoned if it has not returned at `hard` (on Windows the wait can end up to one
/// timer tick, about 15 ms, late).
fn redact_json_bounded(value: &mut Value, soft: Duration, hard: Duration) {
    let start = Instant::now();
    let mut inline_budget = INLINE_TEXT_BYTES;
    if fits_in(value, &mut inline_budget) {
        redact_value(value, &mut Pass::new(start + soft));
        return;
    }
    // Built before the payload moves to the worker, for when the worker does not return in time.
    let markers = markers_only(value);
    let payload = std::mem::take(value);
    let soft_deadline = start + soft;
    let (sender, receiver) = mpsc::channel();
    let worker = thread::Builder::new()
        .name("yalper-redact".into())
        .spawn(move || {
            let mut payload = payload;
            redact_value(&mut payload, &mut Pass::new(soft_deadline));
            // The receiver is gone if the call already returned the markers.
            let _ = sender.send(payload);
        });
    if worker.is_err() {
        // The payload was dropped with the closure; nothing raw is kept.
        *value = markers;
        return;
    }
    // Short waits: a long timed wait was measured ending about 50 ms late on macOS CI (timer leeway).
    let hard_deadline = start + hard;
    *value = loop {
        let left = hard_deadline.saturating_duration_since(Instant::now());
        if left.is_zero() {
            break markers;
        }
        match receiver.recv_timeout(left.min(WAIT_SLICE)) {
            Ok(redacted) => break redacted,
            Err(mpsc::RecvTimeoutError::Timeout) => {}
            // The worker panicked.
            Err(mpsc::RecvTimeoutError::Disconnected) => break markers,
        }
    };
}

/// Whether the strings and keys of `value` hold at most `budget` bytes, each counting
/// [`STRING_COST_BYTES`] more. Stops as soon as they do not.
fn fits_in(value: &Value, budget: &mut usize) -> bool {
    fn charge(text: &str, budget: &mut usize) -> bool {
        match budget.checked_sub(text.len() + STRING_COST_BYTES) {
            Some(left) => {
                *budget = left;
                true
            }
            None => false,
        }
    }
    match value {
        Value::String(text) => charge(text, budget),
        Value::Array(items) => items.iter().all(|item| fits_in(item, budget)),
        Value::Object(map) => map
            .iter()
            .all(|(key, item)| charge(key, budget) && fits_in(item, budget)),
        Value::Null | Value::Bool(_) | Value::Number(_) => true,
    }
}

/// `value` with every string and key replaced by its truncation marker.
fn markers_only(value: &Value) -> Value {
    match value {
        Value::String(text) if !text.is_empty() => Value::String(truncation_marker(text.len())),
        Value::Array(items) => Value::Array(items.iter().map(markers_only).collect()),
        Value::Object(map) => {
            let mut markers = Map::new();
            let mut taken = HashMap::new();
            for (key, item) in map {
                let key = if key.is_empty() {
                    key.clone()
                } else {
                    truncation_marker(key.len())
                };
                insert_unique(&mut markers, &mut taken, key, markers_only(item));
            }
            Value::Object(markers)
        }
        other => other.clone(),
    }
}

/// Inserts `item` under `key`, or under `key #2`, `key #3`, ... when the key is already taken (two keys
/// that became the same marker or the same redacted text). `taken` holds the next suffix to try per key,
/// so many equal keys cost linear time.
fn insert_unique(
    map: &mut Map<String, Value>,
    taken: &mut HashMap<String, usize>,
    key: String,
    item: Value,
) {
    if !map.contains_key(&key) {
        map.insert(key, item);
        return;
    }
    let next = taken.entry(key.clone()).or_insert(2);
    loop {
        let candidate = format!("{key} #{next}");
        *next += 1;
        if !map.contains_key(&candidate) {
            map.insert(candidate, item);
            return;
        }
    }
}

/// The limits of one redaction call.
struct Pass {
    /// Bytes of text that may still be kept.
    budget: usize,
    deadline: Instant,
    /// Set once the deadline has passed: every later string becomes a truncation marker.
    expired: bool,
}

impl Pass {
    fn new(deadline: Instant) -> Self {
        Self {
            budget: MAX_JSON_TEXT_BYTES,
            deadline,
            expired: false,
        }
    }
}

/// The deadline passed during a scan.
struct Expired;

/// Appended to a string that was cut, with the original length so the record shows how much was dropped.
fn truncation_marker(original_bytes: usize) -> String {
    format!("[TRUNCATED: {original_bytes} bytes in total]")
}

fn redact_value(value: &mut Value, pass: &mut Pass) {
    match value {
        Value::String(text) => {
            if let Some(redacted) = redact_string(text, None, pass) {
                *text = redacted;
            }
        }
        Value::Array(items) => {
            // In an argument list, a string after a short flag (`["--password", "..."]`) is scanned with
            // the flag, like an object value with its key.
            let mut flag: Option<String> = None;
            for item in items {
                let Value::String(text) = item else {
                    flag = None;
                    redact_value(item, pass);
                    continue;
                };
                let next_flag = (text.starts_with('-') && text.len() <= 64).then(|| text.clone());
                if let Some(redacted) = redact_string(text, flag.as_deref(), pass) {
                    *text = redacted;
                }
                flag = next_flag;
            }
        }
        Value::Object(map) => {
            let mut entries: Vec<(String, Value)> = std::mem::take(map).into_iter().collect();
            let keys: Vec<Option<String>> = entries
                .iter()
                .map(|(key, _)| redact_string(key, None, pass))
                .collect();
            // Short strings first, so metadata survives when a long value uses up the budget or the time.
            let mut strings: Vec<usize> = (0..entries.len())
                .filter(|&index| entries[index].1.is_string())
                .collect();
            strings.sort_by_key(|&index| entries[index].1.as_str().map_or(0, str::len));
            for index in strings {
                let (key, item) = &mut entries[index];
                if let Value::String(text) = item
                    && let Some(redacted) = redact_string(text, Some(key), pass)
                {
                    *text = redacted;
                }
            }
            for (_, item) in &mut entries {
                if matches!(item, Value::Array(_) | Value::Object(_)) {
                    redact_value(item, pass);
                }
            }
            let mut taken = HashMap::new();
            for ((key, item), redacted) in entries.into_iter().zip(keys) {
                insert_unique(map, &mut taken, redacted.unwrap_or(key), item);
            }
        }
        Value::Null | Value::Bool(_) | Value::Number(_) => {}
    }
}

/// `text` (with `key` when it is that key's value) cut to what is left of the budget, with its secrets
/// masked, or `None` when it is unchanged. Charges the budget.
fn redact_string(text: &str, key: Option<&str>, pass: &mut Pass) -> Option<String> {
    if text.is_empty() {
        return None;
    }
    if pass.expired {
        return Some(truncation_marker(text.len()));
    }
    let limit = pass.budget.min(MAX_STRING_BYTES);
    pass.budget = pass
        .budget
        .saturating_sub(text.len().min(limit) + STRING_COST_BYTES);

    let keep_end = floor_char_boundary(text, limit);
    let scan_end = if keep_end == 0 {
        0
    } else {
        floor_char_boundary(text, limit + CUT_OVERLAP_BYTES)
    };
    let secrets = match string_secrets(&text[..scan_end], key, pass.deadline) {
        Ok(secrets) => secrets,
        Err(Expired) => {
            pass.expired = true;
            return Some(truncation_marker(text.len()));
        }
    };
    if secrets.is_empty() && keep_end == text.len() {
        return None;
    }

    let mut redacted = String::with_capacity(keep_end + 64);
    let mut position = 0;
    for secret in secrets.iter().take_while(|secret| secret.start < keep_end) {
        redacted.push_str(&text[position..secret.start]);
        write!(redacted, "[REDACTED:{}]", RULES[secret.rule].id).unwrap();
        position = secret.end;
    }
    if position < keep_end {
        redacted.push_str(&text[position..keep_end]);
    }
    if keep_end < text.len() {
        redacted.push_str(&truncation_marker(text.len()));
    }
    Some(redacted)
}

/// A byte range of the text to mask, and the rule that found it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Secret {
    start: usize,
    end: usize,
    rule: usize,
}

/// The secrets of a string, on its character boundaries, sorted and merged so that no two overlap: found
/// in the string (with `\"` and `\\` unescaped when it contains `\"`), and with the key it is the value of.
fn string_secrets(
    text: &str,
    key: Option<&str>,
    deadline: Instant,
) -> Result<Vec<Secret>, Expired> {
    // Unescaping keeps every secret of the escaped form findable, so only one form is scanned.
    let mut secrets = if text.contains("\\\"") {
        let (unescaped, unescaped_at) = unescape_quotes(text);
        find_secrets(&unescaped, deadline)?
            .into_iter()
            .map(|secret| Secret {
                start: original_offset(&unescaped_at, secret.start),
                end: original_offset(&unescaped_at, secret.end),
                ..secret
            })
            .collect()
    } else {
        find_secrets(text, deadline)?
    };

    if let Some(key) = key {
        let key = &key[ceil_char_boundary(key, key.len().saturating_sub(PAIR_KEY_BYTES))..];
        let value_end = floor_char_boundary(text, PAIR_VALUE_BYTES);
        let mut pair = format!("\"{key}\": \"{}", &text[..value_end]);
        if value_end == text.len() {
            pair.push('"');
        }
        let value_start = key.len() + 5;
        for secret in find_secrets(&pair, deadline)? {
            let start = secret.start.max(value_start) - value_start;
            let mut end = secret.end.saturating_sub(value_start).min(value_end);
            // A secret that runs into the cut of the value (rules may match up to the end of the text)
            // continues to the end of its token in the real value.
            if end == value_end && value_end < text.len() {
                end = text[value_end..]
                    .find(|c: char| c.is_whitespace() || matches!(c, '"' | '\'' | '`' | ';'))
                    .map_or(text.len(), |offset| value_end + offset);
            }
            if start < end {
                secrets.push(Secret {
                    start,
                    end,
                    ..secret
                });
            }
        }
    }

    for secret in &mut secrets {
        secret.start = floor_char_boundary(text, secret.start);
        secret.end = ceil_char_boundary(text, secret.end);
    }
    secrets.sort_unstable_by_key(|secret| (secret.start, Reverse(secret.end), secret.rule));
    let mut merged: Vec<Secret> = Vec::with_capacity(secrets.len());
    for secret in secrets {
        match merged.last_mut() {
            Some(last) if secret.start < last.end => last.end = last.end.max(secret.end),
            _ => merged.push(secret),
        }
    }
    Ok(merged)
}

/// `text` with `\"` and `\\` unescaped, and the positions in the result of the characters that lost their
/// backslash (see [`original_offset`]).
fn unescape_quotes(text: &str) -> (String, Vec<usize>) {
    let bytes = text.as_bytes();
    let mut unescaped = Vec::with_capacity(bytes.len());
    let mut unescaped_at = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'\\' && matches!(bytes.get(index + 1), Some(b'"' | b'\\')) {
            unescaped_at.push(unescaped.len());
            index += 1;
        }
        unescaped.push(bytes[index]);
        index += 1;
    }
    // Only ASCII backslashes were removed, so the result is still UTF-8.
    let unescaped = String::from_utf8(unescaped).expect("removing ASCII bytes keeps UTF-8 valid");
    (unescaped, unescaped_at)
}

/// The offset in the escaped text of offset `index` in the unescaped text. An unescaped character maps to
/// its backslash, so a secret that ends before `\"` ends before the `\`.
fn original_offset(unescaped_at: &[usize], index: usize) -> usize {
    index + unescaped_at.partition_point(|&position| position < index)
}

/// The secrets the rules find in `text` (unsorted, may overlap), or `Expired` if the deadline passes
/// before a rule runs.
fn find_secrets(text: &str, deadline: Instant) -> Result<Vec<Secret>, Expired> {
    if Instant::now() >= deadline {
        return Err(Expired);
    }
    let mut candidates = [false; RULE_COUNT];
    let mut any = false;
    for hit in keyword_finder().find_overlapping_iter(text) {
        for &rule in KEYWORD_RULES[hit.pattern().as_usize()] {
            candidates[usize::from(rule)] = true;
            any = true;
        }
    }
    if !any {
        return Ok(Vec::new());
    }

    let bytes = text.as_bytes();
    let mut secrets = Vec::new();
    for (index, rule) in RULES.iter().enumerate() {
        if !candidates[index] {
            continue;
        }
        if Instant::now() >= deadline {
            return Err(Expired);
        }
        let Some(regex) = compiled(index) else {
            continue;
        };
        for captures in regex.captures_iter(bytes) {
            let Some(secret) = (if rule.secret_group > 0 {
                captures.get_group(rule.secret_group)
            } else {
                (1..captures.group_len())
                    .filter_map(|group| captures.get_group(group))
                    .find(|group| !group.is_empty())
                    .or_else(|| captures.get_group(0))
            }) else {
                continue;
            };
            let secret_bytes = &bytes[secret.range()];
            // gitleaks drops a match at or below the threshold; keeping the equal case masks slightly more.
            if secret.is_empty()
                || (rule.entropy > 0.0 && shannon_entropy(secret_bytes) < rule.entropy)
                || (rule.letters_only_allowlist && is_letters_only(secret_bytes))
                || (rule.code_allowlist && looks_like_code(secret_bytes))
            {
                continue;
            }
            let masked = if masks_whole_match(rule, captures.group_len()) {
                captures.get_group(0).unwrap_or(secret)
            } else {
                secret
            };
            secrets.push(Secret {
                start: masked.start,
                end: masked.end,
                rule: index,
            });
        }
    }
    Ok(secrets)
}

/// Whether a match of `rule`, whose regex has `group_len` groups counting the whole match, is masked
/// whole. Without a secret group, gitleaks reports the first non-empty group; when a rule has several,
/// they are classifiers or fragments (`jwt-base64` captures the header type, `microsoft-teams-webhook` a
/// 5-character piece), so masking only that group would write most of the secret raw. Yalper's own rules
/// use several groups only as alternatives for the secret.
fn masks_whole_match(rule: &Rule, group_len: usize) -> bool {
    rule.secret_group == 0 && group_len > 2 && !rule.alternative_groups
}

/// gitleaks' `^[a-zA-Z_.-]+$`.
fn is_letters_only(secret: &[u8]) -> bool {
    secret
        .iter()
        .all(|&byte| byte.is_ascii_alphabetic() || matches!(byte, b'_' | b'.' | b'-'))
}

/// Whether a value assigned to a password-like name is code rather than a password, once trailing `,` and
/// `;` are removed: a member access (`process.env.DB_PASSWORD`), a variable (`${DB_PASSWORD}`,
/// `$DB_PASSWORD`), a call without digits (`getPassword()`, `user.getPassword(realm)`, `os.getenv(`), or
/// a generic type (`Option<String>`). Each shape is narrow, so a password with symbols (which has a digit,
/// or a character none of them allow) is still masked.
fn looks_like_code(secret: &[u8]) -> bool {
    let end = secret
        .iter()
        .rposition(|&byte| !matches!(byte, b',' | b';'))
        .map_or(0, |last| last + 1);
    let value = &secret[..end];
    let name_byte = |byte: u8| byte.is_ascii_alphabetic() || matches!(byte, b'_' | b'.' | b'$');
    if is_letters_only(value) {
        return true;
    }
    if let Some(name) = value
        .strip_prefix(b"${")
        .and_then(|rest| rest.strip_suffix(b"}"))
    {
        return !name.is_empty()
            && name
                .iter()
                .all(|&byte| byte.is_ascii_alphanumeric() || byte == b'_');
    }
    if let Some(name) = value.strip_prefix(b"$") {
        return name
            .first()
            .is_some_and(|&byte| byte.is_ascii_uppercase() || byte == b'_')
            && name
                .iter()
                .all(|&byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_');
    }
    if let Some(open) = value.iter().position(|&byte| byte == b'(') {
        let (name, rest) = value.split_at(open);
        let arguments = rest[1..].strip_suffix(b")").unwrap_or(&rest[1..]);
        return !name.is_empty()
            && name.iter().all(|&byte| name_byte(byte))
            && arguments
                .iter()
                .all(|&byte| name_byte(byte) || matches!(byte, b',' | b' '));
    }
    if let Some(open) = value.iter().position(|&byte| byte == b'<') {
        let name = &value[..open];
        return name.first().is_some_and(u8::is_ascii_alphabetic)
            && name
                .iter()
                .all(|&byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b':'))
            && value.ends_with(b">");
    }
    false
}

/// The automaton over all rule keywords, built on first use.
fn keyword_finder() -> &'static AhoCorasick {
    static FINDER: OnceLock<AhoCorasick> = OnceLock::new();
    FINDER.get_or_init(|| {
        AhoCorasick::builder()
            .ascii_case_insensitive(true)
            .build(KEYWORDS)
            .expect("the rule keywords form a valid automaton")
    })
}

/// Rule `index`'s regex, compiled on first use. `None` if it does not compile (a test checks they all do).
fn compiled(index: usize) -> Option<&'static Regex> {
    static COMPILED: [OnceLock<Option<Regex>>; RULE_COUNT] =
        [const { OnceLock::new() }; RULE_COUNT];
    COMPILED[index]
        .get_or_init(|| build_regex(RULES[index].regex).ok())
        .as_ref()
}

/// Compiles a rule's regex with the engine behind the `regex` crate, configured like `regex::bytes`.
///
/// Go's RE2, which gitleaks uses, treats `\w`, `\s`, `\b` and `(?i)` as ASCII, so Unicode mode is off:
/// that is both the faithful port and about 90 times faster to compile. The one-pass DFA is off, since
/// captures only run on the span of a match. The literal prefilter is off for the rules built from
/// gitleaks' semi-generic template, `[\w.-]{0,50}?` before a keyword (101 gitleaks rules, among them
/// `generic-api-key`, which nearly every payload triggers, plus `yalper-password-assignment`): it more
/// than doubles their compile time and does not speed up their search (measured). For the other rules it
/// is cheap and makes the search much faster.
fn build_regex(pattern: &str) -> Result<Regex, Box<meta::BuildError>> {
    let semi_generic = pattern.contains(r"[\w.-]{0,50}?");
    meta::Builder::new()
        .configure(
            meta::Config::new()
                .utf8_empty(false)
                .onepass(false)
                .auto_prefilter(!semi_generic),
        )
        .syntax(syntax::Config::new().unicode(false).utf8(false))
        .build(pattern)
        .map_err(Box::new)
}

/// Shannon entropy in bits per byte. gitleaks counts characters instead; secrets are ASCII, where both agree.
fn shannon_entropy(bytes: &[u8]) -> f64 {
    let mut counts = [0u32; 256];
    for &byte in bytes {
        counts[usize::from(byte)] += 1;
    }
    let length = bytes.len() as f64;
    counts
        .iter()
        .filter(|&&count| count > 0)
        .map(|&count| {
            let frequency = f64::from(count) / length;
            -frequency * frequency.log2()
        })
        .sum()
}

fn floor_char_boundary(text: &str, mut index: usize) -> usize {
    if index >= text.len() {
        return text.len();
    }
    while !text.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn ceil_char_boundary(text: &str, mut index: usize) -> usize {
    while !text.is_char_boundary(index) {
        index += 1;
    }
    index
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    const ALNUM: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    const UPPER_BASE32: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
    const DIGITS: &[u8] = b"0123456789";

    /// A deterministic random-looking string. Fake secrets are built at run time from a prefix and this, so
    /// no complete token appears in the source.
    fn fake(alphabet: &[u8], length: usize, seed: u64) -> String {
        let mut state = seed;
        (0..length)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                char::from(alphabet[(state >> 33) as usize % alphabet.len()])
            })
            .collect()
    }

    fn redacted(text: &str) -> String {
        redact_str(text).unwrap_or_else(|| text.to_owned())
    }

    /// Asserts that `secret` is gone from the redacted `text`, replaced by `rule`'s marker, and returns the
    /// redacted text.
    #[track_caller]
    fn assert_masked(text: &str, secret: &str, rule: &str) -> String {
        let result = redacted(text);
        assert!(!result.contains(secret), "secret left in {result:?}");
        assert!(
            result.contains(&format!("[REDACTED:{rule}]")),
            "no {rule} marker in {result:?}"
        );
        result
    }

    fn group_len(rule: &Rule) -> usize {
        build_regex(rule.regex)
            .unwrap_or_else(|error| panic!("rule {} does not compile: {error}", rule.id))
            .group_info()
            .group_len(regex_automata::PatternID::ZERO)
    }

    #[test]
    fn every_rule_compiles_without_unicode() {
        let gitleaks = RULES.iter().filter(|rule| !rule.id.starts_with("yalper-"));
        assert_eq!(
            gitleaks.count(),
            221,
            "gitleaks v8.30.1 has 221 regex rules"
        );
        for rule in &RULES {
            assert!(
                rule.secret_group < group_len(rule),
                "rule {}: secret group {} does not exist",
                rule.id,
                rule.secret_group
            );
        }
    }

    #[test]
    fn rules_with_several_groups_and_no_secret_group_mask_the_whole_match() {
        let mut whole = Vec::new();
        for rule in &RULES {
            let groups = group_len(rule);
            if masks_whole_match(rule, groups) {
                assert!(rule.secret_group == 0 && groups > 2, "{}", rule.id);
                whole.push(rule.id);
            } else {
                // A rule masks its secret group, its only group, (no group) the whole match, or (Yalper
                // rules) the first of its alternative groups.
                assert!(
                    rule.secret_group > 0 || groups <= 2 || rule.alternative_groups,
                    "{}",
                    rule.id
                );
            }
        }
        for id in [
            "jwt-base64",
            "microsoft-teams-webhook",
            "kubernetes-secret-yaml",
        ] {
            assert!(whole.contains(&id), "{id} not in {whole:?}");
        }
    }

    #[test]
    fn letters_only_allowlist_is_on_generic_api_key_only_among_gitleaks_rules() {
        let allowlisted: Vec<&str> = RULES
            .iter()
            .filter(|rule| rule.letters_only_allowlist)
            .map(|rule| rule.id)
            .collect();
        assert_eq!(
            allowlisted,
            [
                "generic-api-key",
                "yalper-password-assignment",
                "yalper-password-value",
                "yalper-bearer-token"
            ]
        );
    }

    #[test]
    fn every_rule_is_reachable_through_a_lowercase_keyword() {
        let mut reachable = [false; RULE_COUNT];
        for (keyword, rules) in KEYWORDS.iter().zip(KEYWORD_RULES) {
            assert_eq!(*keyword, keyword.to_ascii_lowercase());
            for &rule in rules {
                reachable[usize::from(rule)] = true;
            }
        }
        assert!(reachable.iter().all(|&reachable| reachable));
    }

    #[test]
    fn cloud_provider_access_keys() {
        let aws = format!("AKIA{}", fake(UPPER_BASE32, 16, 1));
        let text = format!("[default]\naws_access_key_id={aws}\nregion=eu-west-3\n");
        let result = redacted(&text);
        assert!(!result.contains(&aws), "{result:?}");
        assert!(result.ends_with("]\nregion=eu-west-3\n"), "{result:?}");
        assert_masked(&format!("id {aws} in use"), &aws, "aws-access-token");

        let gcp = format!("AIza{}", fake(ALNUM, 35, 2));
        assert_masked(&format!("maps.load('{gcp}')"), &gcp, "gcp-api-key");
    }

    #[test]
    fn github_tokens() {
        let classic = format!("ghp_{}", fake(ALNUM, 36, 3));
        let result = assert_masked(
            &format!("git clone https://{classic}@github.com/o/r"),
            &classic,
            "github-pat",
        );
        assert_eq!(
            result,
            "git clone https://[REDACTED:github-pat]@github.com/o/r"
        );

        let fine_grained = format!("github_pat_{}", fake(ALNUM, 82, 4));
        assert_masked(
            &format!("use {fine_grained} here"),
            &fine_grained,
            "github-fine-grained-pat",
        );
    }

    #[test]
    fn llm_provider_api_keys() {
        let anthropic = format!("sk-ant-api03-{}AA", fake(ALNUM, 93, 5));
        assert_masked(
            &format!("client = Client('{anthropic}')"),
            &anthropic,
            "anthropic-api-key",
        );

        let openai = format!(
            "sk-proj-{}T3BlbkFJ{}",
            fake(ALNUM, 74, 6),
            fake(ALNUM, 74, 7)
        );
        assert_masked(
            &format!("OPENAI_API_KEY={openai}\n"),
            &openai,
            "openai-api-key",
        );

        let huggingface = format!(
            "hf_{}",
            fake(b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJ", 34, 8)
        );
        assert_masked(
            &format!("login {huggingface}\n"),
            &huggingface,
            "huggingface-access-token",
        );
    }

    #[test]
    fn slack_tokens() {
        let bot = format!(
            "xoxb-{}-{}-{}",
            fake(DIGITS, 12, 9),
            fake(DIGITS, 13, 10),
            fake(ALNUM, 24, 11)
        );
        assert_masked(&format!("SLACK={bot} ./post.sh"), &bot, "slack-bot-token");

        let webhook = format!("https://hooks.slack.com/services/{}", fake(ALNUM, 44, 12));
        assert_masked(
            &format!("curl -X POST {webhook}"),
            &webhook,
            "slack-webhook-url",
        );
    }

    #[test]
    fn private_key_block() {
        let body: Vec<String> = (0..12).map(|line| fake(ALNUM, 64, 100 + line)).collect();
        let block = format!(
            "-----BEGIN {kind} KEY-----\n{body}\n-----END {kind} KEY-----",
            kind = "RSA PRIVATE",
            body = body.join("\n")
        );
        let result = assert_masked(
            &format!("cat id_rsa\n{block}\ndone"),
            &body[5],
            "private-key",
        );
        assert_eq!(result, "cat id_rsa\n[REDACTED:private-key]\ndone");
    }

    #[test]
    fn json_web_token() {
        let jwt = format!(
            "eyJ{}.eyJ{}.{}",
            fake(ALNUM, 33, 13),
            fake(ALNUM, 60, 14),
            fake(ALNUM, 43, 15)
        );
        assert_masked(&format!("Cookie: session={jwt}; Path=/"), &jwt, "jwt");
    }

    #[test]
    fn generic_assignments() {
        let password = fake(ALNUM, 20, 16);
        let result = assert_masked(
            &format!("password={password}"),
            &password,
            "generic-api-key",
        );
        assert_eq!(result, "password=[REDACTED:generic-api-key]");

        let api_key = fake(ALNUM, 32, 17);
        let result = assert_masked(
            &format!("export API_KEY=\"{api_key}\"\n"),
            &api_key,
            "generic-api-key",
        );
        assert_eq!(result, "export API_KEY=\"[REDACTED:generic-api-key]\"\n");

        let secret = fake(ALNUM, 40, 18);
        assert_masked(
            &format!("{{\"client_secret\": \"{secret}\"}}"),
            &secret,
            "generic-api-key",
        );
    }

    #[test]
    fn low_entropy_values_are_kept() {
        // Below the generic rule's 3.5 bits per byte, as in gitleaks.
        for text in ["password=aaaaaaaaaaaaaaaa", "api_key = 1111111111222222"] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn secrets_inside_tool_input_and_tool_response() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 19));
        let password = fake(ALNUM, 24, 20);
        let mut payload = json!({
            "session_id": "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71",
            "hook_event_name": "PostToolUse",
            "tool_name": "Bash",
            "tool_input": {
                "command": format!("GH_TOKEN={github} gh pr list"),
                "env": { "nested": [1, true, null, { "deeper": format!("using {github}") }] },
            },
            "tool_response": {
                "stdout": format!("connecting with db_password: {password}\nok\n"),
                "stderr": "",
                "interrupted": false,
            },
        });
        redact_json(&mut payload);
        let text = payload.to_string();
        assert!(
            !text.contains(&github) && !text.contains(&password),
            "{text}"
        );
        assert_eq!(
            payload["tool_input"]["env"]["nested"][3]["deeper"],
            "using [REDACTED:github-pat]"
        );
        assert_eq!(
            payload["tool_response"]["stdout"],
            "connecting with db_password: [REDACTED:generic-api-key]\nok\n"
        );
        assert_eq!(
            payload["session_id"],
            "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71"
        );
        assert_eq!(payload["tool_input"]["env"]["nested"][0], 1);
        assert_eq!(payload["tool_response"]["interrupted"], false);
    }

    #[test]
    fn object_keys_are_redacted_in_place() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 21));
        let mut value = json!({ "a": 1, format!("token {github}"): 2, "z": 3 });
        redact_json(&mut value);
        let keys: Vec<&String> = value.as_object().unwrap().keys().collect();
        assert_eq!(keys.len(), 3);
        assert!(keys.iter().all(|key| !key.contains(&github)), "{keys:?}");
        assert_eq!(value["token [REDACTED:github-pat]"], 2);
    }

    #[test]
    fn git_shas_uuids_code_and_prose_are_unchanged() {
        let samples = [
            "commit 9fceb02d0ae598e95dc970b74767f19372d61af8\nAuthor: Dev <dev@example.com>\n\n    Fix parser\n",
            "3f786850e387550fdab836ed7e6dc881de23001b a1b2c3d HEAD@{0}: checkout: moving from main to fix",
            "session 4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71 resumed (request 0d9e3c3a-12f4-4bb1-9d0e-8f6f2a0c5b7e)",
            "fn verify(password: &str, hash: &PasswordHash) -> Result<(), Error> {\n    \
             let token = tokens.next().ok_or(Error::MissingToken)?;\n    \
             let api_key = env::var(\"API_KEY\")?;\n    \
             let key = cache.key_for(&request.path);\n    \
             headers.insert(\"Authorization\", format!(\"Bearer {}\", token.value()));\n    \
             Ok(())\n}\n",
            "export function refresh(session) {\n  if (!session.accessToken) { throw new Error('missing token'); }\n  \
             return fetch(`${API_BASE}/auth/refresh`, { method: 'POST', credentials: 'include' });\n}\n",
            "$ cargo test --workspace\n   Compiling yalper v0.1.0\n    Finished `test` profile in 4.21s\n\
             test store::tests::keys_are_unique ... ok\ntest result: ok. 93 passed; 0 failed\n",
            "They asked for the API docs and the access key rotation policy. Keys must be rotated every \
             90 days, and the secret store keeps the old token for a week.",
            "R\u{e9}sum\u{e9}: na\u{ef}ve caf\u{e9}, \u{6771}\u{4eac}, \u{1f389}, \u{43a}\u{43b}\u{44e}\u{447}.",
        ];
        for text in samples {
            assert_eq!(redact_str(text), None, "changed: {text:?}");
        }
    }

    #[test]
    fn identifier_assignments_are_kept_but_values_with_digits_are_masked() {
        // gitleaks' letters-only allowlist on generic-api-key.
        for text in [
            "const apiKey = process.env.API_KEY;",
            "const secretName = config.secretName;",
            "token = response.access_token_value",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
        let value = format!("process.env.{}", fake(ALNUM, 12, 30));
        let result = assert_masked(
            &format!("const apiKey = {value};"),
            &value,
            "generic-api-key",
        );
        assert_eq!(result, "const apiKey = [REDACTED:generic-api-key];");
    }

    #[test]
    fn jwt_in_base64_is_masked_whole() {
        // `ZXlK` + `aGJHY2lPaU` is `{"alg":` base64-encoded twice; the rule's groups only name the header.
        let token = format!("ZXlKaGJHY2lPaU{}", fake(ALNUM, 120, 31));
        let result = assert_masked(&format!("seen {token} (expired)"), &token, "jwt-base64");
        assert_eq!(result, "seen [REDACTED:jwt-base64] (expired)");
    }

    #[test]
    fn teams_webhook_is_masked_whole() {
        let hex = |length, seed| fake(b"0123456789abcdef", length, seed);
        let guid = |seed: u64| {
            format!(
                "{}-{}-{}-{}-{}",
                hex(8, seed),
                hex(4, seed + 1),
                hex(4, seed + 2),
                hex(4, seed + 3),
                hex(12, seed + 4)
            )
        };
        let webhook = format!(
            "https://contoso.webhook.office.com/webhookb2/{}@{}/IncomingWebhook/{}/{}",
            guid(40),
            guid(50),
            hex(32, 60),
            guid(70)
        );
        let result = assert_masked(
            &format!("curl {webhook} -d @msg.json"),
            &webhook[60..],
            "microsoft-teams-webhook",
        );
        assert_eq!(
            result,
            "curl [REDACTED:microsoft-teams-webhook] -d @msg.json"
        );
    }

    #[test]
    fn sonar_token_uses_the_secret_group() {
        let token = format!("squ_{}", fake(b"0123456789abcdef", 40, 32));
        let result = assert_masked(&format!("sonar.login={token}\n"), &token, "sonar-api-token");
        assert_eq!(result, "sonar.login=[REDACTED:sonar-api-token]\n");
    }

    #[test]
    fn a_key_and_its_value_are_scanned_together() {
        let password = fake(ALNUM, 18, 33);
        let api_key = fake(ALNUM, 32, 34);
        let bearer = fake(ALNUM, 40, 35);
        let opaque = fake(ALNUM, 30, 36);
        let mut input = json!({
            "server": "db",
            "password": password,
            "options": { "api_key": api_key, "retries": 3 },
            "headers": [{ "Authorization": format!("Bearer {bearer}"), "X-Auth-Token": opaque }],
        });
        redact_json(&mut input);
        let text = input.to_string();
        for secret in [&password, &api_key, &bearer, &opaque] {
            assert!(!text.contains(secret.as_str()), "{secret} left in {text}");
        }
        assert_eq!(input["password"], "[REDACTED:generic-api-key]");
        assert_eq!(input["server"], "db");
        assert_eq!(input["options"]["retries"], 3);
        assert_eq!(
            input["headers"][0]["X-Auth-Token"],
            "[REDACTED:generic-api-key]"
        );
    }

    #[test]
    fn partial_private_key_is_masked_to_the_end() {
        let lines: Vec<String> = (0..6).map(|line| fake(ALNUM, 64, 200 + line)).collect();
        let head = format!(
            "$ head -n 7 id_rsa\n-----BEGIN {} KEY-----\n{}",
            "OPENSSH PRIVATE",
            lines.join("\n")
        );
        let result = redacted(&head);
        assert_eq!(
            result,
            "$ head -n 7 id_rsa\n[REDACTED:yalper-private-key-partial]"
        );

        // Escaped newlines, as in a JSON string inside a log line.
        let escaped = format!(
            "key=\"-----BEGIN {} KEY-----\\n{}\\n\"",
            "EC PRIVATE", lines[0]
        );
        assert_masked(&escaped, &lines[0], "yalper-private-key-partial");

        // On one line, or with spaces instead of newlines.
        for separator in ["", " "] {
            let text = format!(
                "pasted -----BEGIN {} KEY-----{separator}{}",
                "RSA PRIVATE",
                lines[..3].join(separator)
            );
            let result = assert_masked(&text, &lines[2], "yalper-private-key-partial");
            assert_eq!(result, "pasted [REDACTED:yalper-private-key-partial]");
        }

        // Header lines before the body: legacy encrypted PEM, and armored PGP (real or escaped newlines).
        let short: Vec<String> = (0..3).map(|line| fake(ALNUM, 44, 300 + line)).collect();
        let pem = format!(
            "-----BEGIN RSA {} KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,{}\n\n{}",
            "PRIVATE",
            fake(b"0123456789ABCDEF", 32, 310),
            short.join("\n")
        );
        assert_eq!(redacted(&pem), "[REDACTED:yalper-private-key-partial]");
        for newline in ["\n", "\\n"] {
            let pgp = format!(
                "$ head -4 key.asc{newline}-----BEGIN PGP {} KEY BLOCK-----{newline}Comment: work laptop{newline}{newline}{}",
                "PRIVATE", short[0]
            );
            let result = assert_masked(&pgp, &short[0], "yalper-private-key-partial");
            assert!(result.starts_with("$ head -4 key.asc"), "{result}");
        }

        // A header in code or in prose, without a key body, leaves the rest of the text alone.
        for text in [
            "if pem.starts_with(\"-----BEGIN RSA PRIVATE KEY-----\") {\n    return Kind::Rsa;\n}\n",
            "const HEADER: &str = \"-----BEGIN PRIVATE KEY-----\\n\";\nfn parse(text: &str) {}\n",
            "Paste the key, which starts with -----BEGIN OPENSSH PRIVATE KEY-----\nand ends with the END line, \
             into the settings page. Never commit it.\n",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn passwords_with_symbols_are_masked() {
        for (text, password) in [
            ("DB_PASSWORD=P@ssw0rd!2024xQ\n", "P@ssw0rd!2024xQ"),
            (
                "POSTGRES_PASSWORD: \"S3cr3t#Pass!word\"\n",
                "S3cr3t#Pass!word",
            ),
            ("{\"password\": \"Tr0ub4dor&3xyz!Q\"}", "Tr0ub4dor&3xyz!Q"),
            ("DB_PASSWORD=P@ss(w0rd)!2024xQ\n", "P@ss(w0rd)!2024xQ"),
            ("password: \"Xk9#mQ2(vL7!pR4z\"\n", "Xk9#mQ2(vL7!pR4z"),
            ("{\"password\":\"Tr0ub4(dor&3\"}", "Tr0ub4(dor&3"),
            ("DB_PASSWORD=a1;b2,c3<d4e5f6 next\n", "a1;b2,c3<d4e5f6"),
        ] {
            let result = redacted(text);
            assert!(!result.contains(password), "{result}");
            assert!(
                result.contains("[REDACTED:yalper-password-value]"),
                "{result}"
            );
        }
        let mut value = json!({ "env": { "password": "Tr0ub4dor&3xyz!Q" } });
        redact_json(&mut value);
        assert_eq!(value["env"]["password"], "[REDACTED:yalper-password-value]");

        for text in [
            "DB_PASSWORD=${DB_PASSWORD}",
            "password: ${DB_PASSWORD}",
            "let password = getPassword();",
            "password = user.getPassword(realm)",
            "struct Login { password: Option<String>, hash: Vec<u8> }",
            "password: process.env.DB_PASSWORD,",
            "password = self.password_field;",
            "export DB_PASSWORD=$DB_PASSWORD_FROM_VAULT",
            "password = os.getenv(\"DB_PASSWORD\")",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn random_passwords_with_symbols_never_leak() {
        const CHARACTERS: &[u8] =
            b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+[]{}?/|~";
        const COUNT: usize = 3000;
        let characters = fake(CHARACTERS, 15 * COUNT, 1000);
        let digits = fake(DIGITS, 2 * COUNT, 2000);
        let mut leaks = Vec::new();
        for index in 0..COUNT {
            // 15 random characters and a digit at a random place, so no password is letters only.
            let mut password = characters[15 * index..15 * (index + 1)].to_owned();
            let place = usize::from(digits.as_bytes()[2 * index] - b'0');
            password.insert_str(place, &digits[2 * index + 1..2 * index + 2]);
            for text in [
                format!("DB_PASSWORD={password}\n"),
                format!("password: \"{password}\"\n"),
            ] {
                let result = redacted(&text);
                // Any 8 characters of the password written raw count as a leak.
                if (0..=password.len() - 8)
                    .any(|start| result.contains(&password[start..start + 8]))
                {
                    leaks.push(text);
                }
            }
        }
        assert_eq!(leaks, Vec::<String>::new());
    }

    #[test]
    fn command_line_passwords_are_masked() {
        let password = fake(ALNUM, 12, 44);
        for command in [
            format!("mysql -u root -p{password} shop"),
            format!("mysqldump -h db -uroot -p'{password}' shop > dump.sql"),
            format!("sshpass -p {password} ssh deploy@host"),
            format!("docker login -u ci -p {password} registry.example.com"),
            format!("helm registry login ghcr.io --username ci --password={password}"),
            format!("app --password {password} --verbose"),
        ] {
            let result = redacted(&command);
            assert!(!result.contains(&password), "{result}");
        }
        let mut argv = json!(["psql-wrapper", "--password", password]);
        redact_json(&mut argv);
        assert!(!argv.to_string().contains(&password), "{argv}");
        let mut args = json!({ "args": format!("[\"--password\", \"{password}\"]") });
        redact_json(&mut args);
        assert!(!args.to_string().contains(&password), "{args}");

        for text in [
            "mysql -u root -p shop",
            "mysql -h db -P3306 -u app shop",
            "docker login --password-stdin ghcr.io",
            "app --password $APP_PASSWORD",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn a_long_value_found_through_its_key_is_masked_to_the_end_of_the_token() {
        let key = fake(
            b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
            2000,
            45,
        );
        let mut value = json!({ "data": { "tls.key": format!("{key}=="), "tls.crt": "n/a" } });
        redact_json(&mut value);
        assert_eq!(value["data"]["tls.key"], "[REDACTED:generic-api-key]");

        let mut value = json!({ "secret": format!("{key} and more text") });
        redact_json(&mut value);
        assert_eq!(value["secret"], "[REDACTED:generic-api-key] and more text");
    }

    #[test]
    fn url_passwords_are_masked() {
        for (scheme, user) in [
            ("postgres", "admin"),
            ("mongodb+srv", "app"),
            ("redis", ""),
            ("https", "deploy"),
        ] {
            let password = fake(ALNUM, 14, 37);
            let text = format!("connect {scheme}://{user}:{password}@db.internal:5432/app");
            let result = assert_masked(&text, &password, "yalper-url-password");
            assert_eq!(
                result,
                format!(
                    "connect {scheme}://{user}:[REDACTED:yalper-url-password]@db.internal:5432/app"
                )
            );
        }
        for text in [
            "http://localhost:8080/api/v1?user=a@b",
            "ssh://git@github.com:22/org/repo.git",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn pass_and_pwd_assignments_are_masked() {
        for name in ["DB_PASS", "DB_PWD", "smtp.pass", "MYSQL_ROOT_PWD"] {
            let password = fake(ALNUM, 16, 38);
            let result = assert_masked(
                &format!("{name}={password}\n"),
                &password,
                "yalper-password-assignment",
            );
            assert_eq!(
                result,
                format!("{name}=[REDACTED:yalper-password-assignment]\n")
            );
        }
        for text in [
            "DB_PASS=aaaaaaaaaaaaaaaa",
            "bypass = settings.bypassCache",
            "    pass\n",
        ] {
            assert_eq!(redact_str(text), None, "{text}");
        }
    }

    #[test]
    fn bearer_tokens_are_masked() {
        let token = fake(ALNUM, 32, 39);
        let result = assert_masked(
            &format!("GET /v1/me HTTP/1.1\nAuthorization: Bearer {token}\nAccept: */*\n"),
            &token,
            "yalper-bearer-token",
        );
        assert_eq!(
            result,
            "GET /v1/me HTTP/1.1\nAuthorization: Bearer [REDACTED:yalper-bearer-token]\nAccept: */*\n"
        );
        assert_eq!(redact_str("Use Bearer authentication for the API."), None);
        // In a curl command, gitleaks' curl-auth-header rule masks the whole header.
        let curl = format!("curl -H 'Authorization: Bearer {token}' https://api.example.com");
        assert!(!redacted(&curl).contains(&token));
    }

    #[test]
    fn json_escaped_twice_is_scanned_unescaped() {
        let secret = fake(ALNUM, 24, 40);
        let line = format!("{{\"log\": \"{{\\\"client_secret\\\": \\\"{secret}\\\"}}\"}}");
        let result = assert_masked(&line, &secret, "generic-api-key");
        assert_eq!(
            result,
            "{\"log\": \"{\\\"client_secret\\\": \\\"[REDACTED:generic-api-key]\\\"}\"}"
        );
    }

    #[test]
    fn metadata_survives_a_payload_over_the_budget() {
        let content = "line of the new file\n".repeat(MAX_STRING_BYTES / 20);
        let original = "line of the old file\n".repeat(MAX_STRING_BYTES / 20);
        let patch: Vec<Value> = (0..2000)
            .map(|line| json!({ "oldStart": line, "lines": [format!("-old {line}"), format!("+new {line}")] }))
            .collect();
        let mut payload = json!({
            "session_id": "4f2c8e1a-7b3d-4c9e-a1f0-2d6b8e5c3a71",
            "transcript_path": "/home/dev/.claude/projects/demo/session.jsonl",
            "cwd": "/home/dev/demo",
            "hook_event_name": "PostToolUse",
            "tool_name": "Write",
            "tool_input": { "file_path": "/home/dev/demo/big.txt", "content": content },
            "tool_response": {
                "type": "update",
                "filePath": "/home/dev/demo/big.txt",
                "content": content,
                "originalFile": original,
                "structuredPatch": patch,
            },
            "tool_use_id": "toolu_01ABCDEFGH",
        });
        redact_json(&mut payload);
        assert_eq!(payload["tool_use_id"], "toolu_01ABCDEFGH");
        assert_eq!(payload["tool_name"], "Write");
        assert_eq!(
            payload["transcript_path"],
            "/home/dev/.claude/projects/demo/session.jsonl"
        );
        assert_eq!(payload["tool_response"]["type"], "update");
        assert_eq!(
            payload["tool_response"]["filePath"],
            "/home/dev/demo/big.txt"
        );
        assert_eq!(payload["tool_input"]["file_path"], "/home/dev/demo/big.txt");
        assert_eq!(payload["hook_event_name"], "PostToolUse");
        let structured = payload["tool_response"]["structuredPatch"].to_string();
        assert!(structured.contains("[TRUNCATED: "), "the budget ran out");
    }

    #[test]
    fn after_the_deadline_strings_become_markers() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 41));
        let mut payload = json!({
            "a": format!("token {github}"),
            "b": "same length key",
            "cc": ["plain", ""],
            "ddd": 1,
        });
        redact_json_within(&mut payload, Duration::ZERO);
        assert_eq!(
            payload,
            json!({
                "[TRUNCATED: 1 bytes in total]": "[TRUNCATED: 46 bytes in total]",
                "[TRUNCATED: 1 bytes in total] #2": "[TRUNCATED: 15 bytes in total]",
                "[TRUNCATED: 2 bytes in total]": ["[TRUNCATED: 5 bytes in total]", ""],
                "[TRUNCATED: 3 bytes in total]": 1,
            })
        );
    }

    /// `{"tool_response": [text, text, text, text]}`.
    fn four_copies(text: &str) -> Value {
        json!({ "tool_response": [text, text, text, text] })
    }

    #[test]
    fn hostile_text_stops_at_the_deadline_without_leaking() {
        // Every keyword followed by an assignment, so every rule runs over the whole string. Unoptimized
        // test builds cannot finish one copy in time.
        let keywords = KEYWORDS.join("_v = \"Zq8Lx3Vn7Rb2Kt9Ws4Pd6\"\n");
        let mut text = keywords.repeat(MAX_STRING_BYTES / keywords.len() + 1);
        text.truncate(MAX_STRING_BYTES - 100);
        text.push_str(&format!("ghp_{}", fake(ALNUM, 36, 42)));
        let mut payload = four_copies(&text);
        let start = Instant::now();
        redact_json_within(&mut payload, DEADLINE);
        let elapsed = start.elapsed();
        assert!(elapsed < Duration::from_secs(1), "took {elapsed:?}");
        // Either the worker stopped before a rule run (the key was done by then) or the call gave up on
        // it (every key is a marker too).
        let (key, strings) = payload.as_object().unwrap().iter().next().unwrap();
        assert!(
            key == "tool_response" || *key == truncation_marker(13),
            "{key}"
        );
        let marker = Value::String(truncation_marker(text.len()));
        assert_eq!(strings, &json!([marker, marker, marker, marker]));
    }

    #[test]
    fn a_worker_stuck_in_one_rule_is_abandoned_at_the_deadline() {
        // `pwd` and up to 7 random name characters, repeated: one run of the password rules over this
        // takes about half a second even in a release build. With no early stop, only the hard deadline
        // returns.
        let lengths = fake(b"01234567", MAX_STRING_BYTES / 3, 43);
        let names = fake(
            b"abcdefghijklmnopqrstuvwxyz0123456789_.-",
            MAX_STRING_BYTES,
            44,
        );
        let (mut text, mut position) = (String::new(), 0);
        for length in lengths.bytes().map(|digit| usize::from(digit - b'0')) {
            if text.len() >= MAX_STRING_BYTES {
                break;
            }
            text.push_str("pwd");
            text.push_str(&names[position..position + length]);
            position += length;
        }
        let mut payload = four_copies(&text);
        let start = Instant::now();
        redact_json_bounded(&mut payload, Duration::from_secs(600), DEADLINE);
        let elapsed = start.elapsed();
        assert!(elapsed < Duration::from_secs(1), "took {elapsed:?}");
        let marker = truncation_marker(text.len());
        assert_eq!(
            payload,
            json!({ truncation_marker(13): [marker, marker, marker, marker] })
        );
    }

    #[test]
    fn non_ascii_text_around_a_secret_is_kept() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 22));
        let text = format!("cl\u{e9}: \u{ab}{github}\u{bb} \u{6771}\u{4eac}\u{1f389}");
        assert_eq!(
            redacted(&text),
            "cl\u{e9}: \u{ab}[REDACTED:github-pat]\u{bb} \u{6771}\u{4eac}\u{1f389}"
        );
    }

    #[test]
    fn overlapping_matches_become_one_marker() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 23));
        let result = redacted(&format!("GITHUB_TOKEN={github}\n"));
        assert_eq!(result.matches("[REDACTED:").count(), 1, "{result}");
        assert!(
            result.starts_with("GITHUB_TOKEN=[REDACTED:") && result.ends_with("]\n"),
            "{result}"
        );
    }

    #[test]
    fn long_strings_are_cut_with_their_length() {
        let text = "x".repeat(MAX_STRING_BYTES + 10);
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}[TRUNCATED: {} bytes in total]",
                "x".repeat(MAX_STRING_BYTES),
                text.len()
            )
        );

        // A cut inside a multi-byte character moves back to the character's start.
        let text = format!(
            "{}\u{e9}{}",
            "x".repeat(MAX_STRING_BYTES - 1),
            "y".repeat(10)
        );
        let result = redact_str(&text).unwrap();
        assert_eq!(
            result,
            format!(
                "{}{}",
                "x".repeat(MAX_STRING_BYTES - 1),
                truncation_marker(text.len())
            )
        );
    }

    #[test]
    fn a_secret_across_the_cut_leaves_no_prefix() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 24));
        let mut text = "x ".repeat((MAX_STRING_BYTES - 10) / 2);
        text.push_str(&github);
        text.push_str(&" y".repeat(1000));
        let result = redact_str(&text).unwrap();
        assert!(
            !result.contains("ghp_"),
            "secret prefix left before the cut"
        );
        assert!(result.ends_with(&format!(
            "[REDACTED:github-pat]{}",
            truncation_marker(text.len())
        )));
    }

    #[test]
    fn a_secret_only_after_the_cut_is_dropped() {
        let github = format!("ghp_{}", fake(ALNUM, 36, 25));
        let text = format!("{}{github}", "x".repeat(MAX_STRING_BYTES + 100));
        let result = redact_str(&text).unwrap();
        assert!(!result.contains("ghp_") && !result.contains("REDACTED"));
    }

    #[test]
    fn a_json_value_is_cut_to_its_budget() {
        let big = "z".repeat(MAX_STRING_BYTES);
        let mut value = json!({ "parts": [big, big, big, big, big, "short", ""] });
        redact_json(&mut value);
        let parts: Vec<&str> = value["parts"]
            .as_array()
            .unwrap()
            .iter()
            .map(|part| part.as_str().unwrap())
            .collect();
        let kept: usize = parts.iter().map(|part| part.matches('z').count()).sum();
        assert!(kept <= MAX_JSON_TEXT_BYTES, "{kept} bytes kept");
        assert_eq!(parts[0], big);
        assert!(parts[3].ends_with(&truncation_marker(MAX_STRING_BYTES)));
        assert_eq!(parts[4], truncation_marker(MAX_STRING_BYTES));
        assert_eq!(parts[5], truncation_marker(5));
        assert_eq!(parts[6], "");
    }

    #[test]
    fn tiny_strings_use_up_the_budget_too() {
        let count = MAX_JSON_TEXT_BYTES / STRING_COST_BYTES + 10;
        let mut value = Value::Array(vec![Value::from("ey"); count]);
        redact_json(&mut value);
        let items = value.as_array().unwrap();
        assert_eq!(items[0], "ey");
        assert_eq!(items[count - 1], truncation_marker(2));
    }

    #[test]
    fn shannon_entropy_in_bits_per_byte() {
        assert_eq!(shannon_entropy(b"aaaa"), 0.0);
        assert_eq!(shannon_entropy(b"aabb"), 1.0);
        assert_eq!(shannon_entropy(b"abcdefgh"), 3.0);
    }
}
